### ISSUE TITLE
Images needed for homepage

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#143]
The new homepage, created in #142 and based on [the design](https://projects.invisionapp.com/d/main/default/#/console/10245106/218034264/preview), is missing images. These will needed to be created and added before the page goes live.

**Comment by jamiedawsonyoung** [comment]
Closing this issue as the images are there…

**Comment by jamiedawsonyoung** [comment]
Except I can't as I've not got access to the repo ;-)

**Comment by bartaz** [comment]
@jamiedawsonyoung I invited you to the repo. Try if you can close it now.

**Comment by jamiedawsonyoung** [comment]
Thanks @bartaz 👍
