### ISSUE TITLE
Exception when clicking "Enable repos"

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#153]
When clicking 'Enable repos':

> Failed to load resource: the server responded with a status of 404 (Not Found)
> select-repositories:1 Fetch API cannot load https://myapps.developer.ubuntu.com/dev/api/acl/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://build.staging.snapcraft.io' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> bundle.bcb45f3bcd283ac95128.js:43 Uncaught (in promise) TypeError: Cannot read property 'payload' of undefined
>     at t.value (https://build.staging.snapcraft.io/static/bundle.bcb45f3bcd283ac95128.js:43:22271)
>     at t.value (https://build.staging.snapcraft.io/static/bundle.bcb45f3bcd283ac95128.js:43:22719)
>     at Array.map (native)
>     at t.value (https://build.staging.snapcraft.io/static/bundle.bcb45f3bcd283ac95128.js:43:23575)
>     at _renderValidatedComponentWithoutOwnerOrContext (https://build.staging.snapcraft.io/static/bundle.bcb45f3bcd283ac95128.js:57:28535)
>     at _renderValidatedComponent (https://build.staging.snapcraft.io/static/bundle.bcb45f3bcd283ac95128.js:57:28662)
>     at _updateRenderedComponent (https://build.staging.snapcraft.io/static/bundle.bcb45f3bcd283ac95128.js:57:27962)
>     at _performComponentUpdate (https://build.staging.snapcraft.io/static/bundle.bcb45f3bcd283ac95128.js:57:27763)
>     at _.updateComponent (https://build.staging.snapcraft.io/static/bundle.bcb45f3bcd283ac95128.js:57:27041)
>     at _.receiveComponent (https://build.staging.snapcraft.io/static/bundle.bcb45f3bcd283ac95128.js:57:26152)

**Comment by bartaz** [comment]
We have issues with staging currently.

Nodes with older deployments are still accessible, so some requests are sent to old nodes and return 404.

This makes staging quite unusable until we fix that unfortunately.

**Comment by cjwatson** [comment]
I don't think this can be an issue on our end.  It looks much more like a regression in production SCA.

**Comment by cjwatson** [comment]
Actually I think not a regression, but a bug that was there all along.  SCA includes that header in success responses, but not in error responses.  I'll fix this next week.

**Comment by cjwatson** [comment]
OK, I at least had time to write the patch (https://code.launchpad.net/~cjwatson/software-center-agent/cross-origin-acl-on-errors/+merge/317697), though of course we won't be able to get that merged and rolled out until early next week.

**Comment by cjwatson** [comment]
The SCA fix is now on production, so this bug is fixed.
