### ISSUE TITLE
Add Repos… button broken after adding a repo

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#204]
Steps to reproduce:
- Go to the dashboard
- Click Add Repos…
- Select any repo and add it to the canvas
- Click Add Repos… again

What happens:
- The dashboard page refreshes, keeping the user in the same place

What should happen:
- The Add Repos… page should open

**Comment by nottrobin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Clicking "Add repos" after having just adding one creates infinite loop back to the dashboard page](https://trello.com/c/VuxjhlcE/215-bug-clicking-add-repos-after-having-just-adding-one-creates-infinite-loop-back-to-the-dashboard-page)
