### ISSUE TITLE
workflow diagram issues

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#212]
<img width="1038" alt="screen shot 2017-02-23 at 09 04 07" src="https://cloud.githubusercontent.com/assets/1523179/23251990/18141bde-f9a7-11e6-8f15-cd050ad314e4.png">

- The font doesn't match the rest of the website
- The path bends behind different heights draws more attention than the content. Can we make them even?

**Comment by pmahnke** [comment]
that's an export problem of the svg... it looks fine if you have the ubuntu font on your system... which is how we missed it.

I will ask Matthieu James for a new export

**Comment by tiheum** [comment]
Can you try with this attached file?
[workflow_text-to-path.zip](https://github.com/canonical-ols/build.snapcraft.io/files/796173/workflow_text-to-path.zip)

I converted the text objects to vector shapes so it should solve the issue.

**Comment by evandandrea** [comment]
That does solve the text issue. The differing heights of the path bends remains.
