### ISSUE TITLE
Adding an already-added repo fails with a confusing error

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#213]
<img width="718" alt="screen shot 2017-02-23 at 09 14 33" src="https://cloud.githubusercontent.com/assets/1523179/23252409/a206eed8-f9a8-11e6-8021-dc88fb5721ad.png">

We shouldn't show repos on the select-repositories page that have already been added. I know we talked about this earlier in the week, but I couldn't find a card for it.

**Comment by cjwatson** [comment]
Yes, there is a card: https://trello.com/c/jdl05qOn/174-add-new-repo-filter-out-repositories-that-are-already-enabled

**Comment by evandandrea** [comment]
This has since been fixed.
