### ISSUE TITLE
First-time text and progress bar on select-repositories missing

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#214]
<img width="875" alt="screen shot 2017-02-23 at 09 29 17" src="https://cloud.githubusercontent.com/assets/1523179/23253000/cb8a6cf6-f9aa-11e6-9d44-f05d8c4ebd7d.png">

At 9:30am (25dafb9ca8347c4df4e1). Colin reset my account. I went to the front page, then clicked "Set up in minutes". I was brought to the add-repositories page as expected, but the first-time text and progress bar are missing.

**Comment by bartaz** [comment]
Should be fixed by #218

**Comment by evandandrea** [comment]
Yup, sure is.
