### ISSUE TITLE
First added repo with actionables is not expanded [1]

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#224]
<img width="1059" alt="screen shot 2017-02-24 at 09 05 34" src="https://cloud.githubusercontent.com/assets/1523179/23297382/3c10ce40-fa71-11e6-929b-f02a809d4293.png">

The first repo with actionable tasks should be expanded by default (to whatever the first-time text is suggesting the user do) when landing on the dashboard.

**Comment by evandandrea** [comment]
Just confirmed this is still happening on staging. The relevant part of the spec is "First-time flow", "at least one repo…"

**Comment by earnubs** [comment]
See also #363

**Comment by earnubs** [comment]
Fixed in #450 & #484
