### ISSUE TITLE
Redux store structure [15]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#269]
Currently our redux store structure is mostly based on API we call - we have separate reducer per API. We also have a mix of keyed and non-keyed values that make data unwieldy to traverse.

In UI the structure is rather different (combining info from different sources).

Maybe we could structure our store in a way that is closer to what UI shows, not to what API returns.

This way we could avoid spreading data across different reducers.
For example status of name registration is now kept in 2 places: `registerName` reducer (for handling name registration from BSI side) and `store_name` in snaps reducer (when snap was already registered before).

---

Copied from Trello card: https://trello.com/c/IxkkH4ae/251-redux-store-structure
Labels:

**Comment by katiefenn** [comment]
Deferred for discussion

**Comment by earnubs** [comment]
Introducing selectors will help with this, see #450

**Comment by magdalena-mirowicz** [comment]
@earnubs please split this card and size

**Comment by earnubs** [comment]
This ticket should be split roughly along the lines of subject matter:

- github repositories
- snaps in launchpad
- user identification, authentication and authorisation
- routing (not a refactor, but since we're here we may as well ask the question as to whether we need the router binding to state)

**Comment by earnubs** [comment]
@magdalena-mirowicz this card is now split up and estimated in cards linked above.
