### ISSUE TITLE
[API] Allow more SCA requests to be made cross-origin [2]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#272]
We need to get rid of our proxy endpoints so that the `package_upload_request` macaroon doesn't need to go through our servers.

---

Copied from Trello card: https://trello.com/c/2Gh7N9rJ/191-api-allow-more-sca-requests-to-be-made-cross-origin
Labels:

**Comment by nottrobin** [comment]
Priority: 5

A security fix to the store API. It prevents an attacker who gains access to build.snapcraft.io from being able to get further.

**Comment by katiefenn** [comment]
C: 5
K: 5
B: 5

**Comment by sparkiegeek** [comment]
https://code.launchpad.net/~adam-collard/software-center-agent/add-cors-headers/+merge/322856 seeks to add CORS headers to the store so we can address this

**Comment by sparkiegeek** [comment]
This was reverted in #698
