### ISSUE TITLE
Flux standard actions

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#280]
https://github.com/acdlite/flux-standard-action#example

For example don't use separate `_SUCCESS` and `_ERROR` actions, same action with error: true and error payload can be used.

---

Copied from Trello card: https://trello.com/c/ZFxhWt33/10-flux-standard-actions
Labels:

**Comment by katiefenn** [comment]
K: 2,
B: 2,
C: 2,
R: 2

**Comment by earnubs** [comment]
After state refactor and api middleware refactor, and agreeing to contain error in payload if error prop is true, this isn't worth much further consideration.
