### ISSUE TITLE
Only load build details if not in the store already

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#282]
Currently when opening build details page we fetch snap details and builds list (latest 20) even if data about given build is already in the store (from listing).

We shouldn't ask for data that we already have.

Also, it may be possible that given build is not in latest 20, so we should probably try to load data of this particular build, not expecting listing to contain the data.

---

Copied from Trello card: https://trello.com/c/vhc4VEVb/57-only-load-build-details-if-not-in-the-store-already
Labels:

**Comment by katiefenn** [comment]
K: 3,
B: 3,
C: 3,
R: 4

**Comment by katiefenn** [comment]
Duplicates #270
