### ISSUE TITLE
Removing the snapcraft.yaml does not reset the "configured" state

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#291]
---

Copied from Trello card: https://trello.com/c/9vynWiki/330-bug-removing-the-snapcraft-yaml-does-not-reset-the-configured-state
Labels: Bug

**Comment by pmahnke** [comment]
To reproduce:

* Add a repo with a snapcraft.yaml to the dashboard
* Remove the snapcraft.yaml on GitHub
* Refresh the page

What happens:

* The repo still shows as configured
* What should happen:

The repo shows as unconfigured

**Comment by matthewpaulthomas** [comment]
Duplicate of #293.
