### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#292]
- Set up GA account for BSI (separate for staging/production).
- Set up Google Tag Manager in support of munchkin tags.

Comments from trello:

- @bartoszopka can you elaborate on what kind of things could be tracked that would not be there out of the box?
- @evandandrea Anything specific we would like to track (apart from page views) at the beginning? And also please prioritise it.

---

Copied from Trello card: https://trello.com/c/zIJXmJ8C/321-add-google-analytics
Labels:

**Comment by nottrobin** [comment]
To achieve this, we should simply add our standard Google Tag Manager code snippet, and then we can control all the trackers we want through GTM.

``` html
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K92JCQ');</script>
<!-- End Google Tag Manager -->
```

**Comment by earnubs** [comment]
@nottrobin sure you want noscript version?

**Comment by earnubs** [comment]
https://medium.com/@j3y/analytics-with-react-redux-spas-and-google-tag-manager-4d3a55833619#.trwr4dd9f

**Comment by earnubs** [comment]
Adding blocked label wrt requirement for GA account and id.

**Comment by nottrobin** [comment]
@earnubs The ID is GTM-K92JCQ

Yes I think we should have the noscript. It would be good to in theory be able to tell something about people without JavaScript.
