### ISSUE TITLE
Reloading the page after adding a snapcraft.yaml from the template link still shows the "this repo needs a snapcraft.yaml file" message

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#294]
---

Copied from Trello card: https://trello.com/c/ogXzR2mI/335-reloading-the-page-after-adding-a-snapcraft-yaml-from-the-template-link-still-shows-the-this-repo-needs-a-snapcraft-yaml-file-me
Labels: Bug

**Comment by magdalena-mirowicz** [comment]
duplicate of #293
