### ISSUE TITLE
Implement true zero-downtime deployments [3]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#296]
https://trello.com/c/KoV8RvuB/214-fix-production-releases-to-have-a-stable-state-while-releasing was the first stage; this is the more fiddly second stage.  At the moment, we enable the new deployment in haproxy and then disable the old one; in the window between those two, requests can come in to new units, then try to separately fetch JS bundles from the old units and fail.

---

Copied from Trello card: https://trello.com/c/WV8cSieE/216-implement-true-zero-downtime-deployments
Labels:

**Comment by magdalena-mirowicz** [comment]
@cjwatson could you confirm what's the current downtime please?

**Comment by cjwatson** [comment]
@magdalena-mirowicz About a minute.

**Comment by cjwatson** [comment]
Thinking about this.  Switching out the backends atomically was my first thought, but it's not obvious how to do that with relation-driven service definitions.  However, another possibility would be to use haproxy's persistence cookies.  If we tell haproxy to identify each server with a git commit hash (either of its code or of the charm build it's running, whichever's easiest) and then tell it to use persistence cookies in the mode where it honours them unless all the backends with that cookie value have vanished, then we should get roughly the right behaviour: clients will "stick" to a particular version of the app until it goes away.

**Comment by cjwatson** [comment]
Bumping my earlier estimate by another day - I have some idea what to do now after further discussion on #u1-internal, but it will take some experimentation to get it right.

**Comment by cjwatson** [comment]
https://code.launchpad.net/~cjwatson/canonical-mojo-specs/snap-build-assets/+merge/319656
