### ISSUE TITLE
[name not matching] get location of snapcraft.yaml name

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#297]
Handling name mismatch requires a link to snapcraft.yaml file in GitHub.

Currently we only know that file exists, but it may be in one of 3 allowed locations (/snap/snapcraft.yaml, snapcraft.yaml or .snapcraft.yaml), so we need to know where the file is in current repo.

We already have snapcraft_data with a name in it, it should probably be extended to include location of the file.

---

Copied from Trello card: https://trello.com/c/aTaRuaMq/325-name-not-matching-get-location-of-snapcraft-yaml-name
Labels:

**Comment by bartaz** [comment]
This is required before #298 #299 #300 #301 can be completed.
