### ISSUE TITLE
[name not matching] snapcraft.yaml name is registered by someone else [2]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#300]
---

Copied from Trello card: https://trello.com/c/HsTMP9Ni/328-name-not-matching-snapcraft-yaml-name-is-registered-by-someone-else
Labels:

---

TODO:

- [x] add API call to check if name is registered in the store (by anyone)
  - try to request a throwaway package_upload macaroon from the store's /dev/api/acl/ endpoint restricted to the name in question; that will fail if the name is not registered
- [x] add API call to try registering name and interpret 409 conflict to know if name is registered by current user or someone else:
  - try to request a throwaway package_upload macaroon from the store's /dev/api/acl/ endpoint restricted to the name in question; that will fail if the name is not registered
- [x] use API requests to set status of the snap (who owns name from snapcraft.yaml) after user signs in to SSO
- [x] display proper message in UI based on snap status

**Comment by bartaz** [comment]
@cjwatson do we currently have the means to check if name was registered by someone else in the store (without trying to register it and checking error response)?

**Comment by cjwatson** [comment]
@bartaz What's wrong with trying to register it and checking the error response?  That seems like a perfectly reasonable way to do it.  The `register-name` handler returns fine-grained error codes that distinguish between this case and other cases.

**Comment by bartaz** [comment]
@cjwatson It may have a side-effect of registering the name user didn't want to register.

The case is they have some name registered for their snap and different name in snapcraft.yaml. Maybe they just made a typo in the snapcraft.yaml they didn't intent.
We just want to check if the name is registered by a different user so we can suggest them to use different one.

If automatically we will try to register the name just to check if it is already registered we may end up registering the name that was maybe just a typo.

**Comment by cjwatson** [comment]
@bartaz So, it only makes a difference if the name is not registered at all.  In that case BSI can tell the difference as follows:

 - try to request a throwaway `package_upload` macaroon from the store's `/dev/api/acl/` endpoint restricted to the name in question; that will fail if the name is not registered
 - if that succeeds, try `/dev/api/register-name/`, which will return 409 with an `already_registered` code if the name belongs to somebody else

**Comment by bartaz** [comment]
UI for that requires #297 (knowing the location of snapcraft.yaml in repo)

**Comment by matthewpaulthomas** [comment]
(@magdalena-mirowicz Please don’t mark an issue as “Design required” with no explanation why. This has been in the spec since February 7th.)

**Comment by bartaz** [comment]
This task requires adding new info about the snap into application store (and 2 additional API requests to check if name is registered by someone else). Because of technical debt in current state of the app it may take quite significant time (rough estimate [4]). Part of the app store related to this task is planned to be refactored in #465 and it would be best to implement this feature after this refactoring.

**Comment by magdalena-mirowicz** [comment]
consider fixing #299 at the same time

**Comment by bartaz** [comment]
First part of snaps store refactoring was merged (#624), so this task can be implemented without huge overhead.
