### ISSUE TITLE
API to fetch revision number for build [3]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#304]
---

Copied from Trello card: https://trello.com/c/H5JBcwN4/184-api-to-fetch-revision-number-for-build
Labels:

**Comment by magdalena-mirowicz** [comment]
@cjwatson could you try to estimate it please? Thank you

**Comment by cjwatson** [comment]
I've gone for an estimate of three days, since there are several bits to change here all of which need some thought (launchpad-buildd, a Launchpad database patch, and making the Launchpad snap build behaviour record the information returned by launchpad-buildd).

**Comment by magdalena-mirowicz** [comment]
Thanks @cjwatson

**Comment by cjwatson** [comment]
https://bugs.launchpad.net/bugs/1679157

**Comment by cjwatson** [comment]
https://bugs.launchpad.net/launchpad/+bug/1679197

**Comment by cjwatson** [comment]
I initially misunderstood this as asking for something slightly different, and that hasn't landed yet, but the real request (getting the store revision of an uploaded build) is now live on Launchpad production.  Marking this as done.
