### ISSUE TITLE
[repo and build details] Navigation breadcrumb [2]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#310]
---

Copied from Trello card: https://trello.com/c/I69KPPVZ/146-repo-and-build-details-navigation-breadcrumb
Labels:

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.15nyc5j48m1e): “Hierarchy navigation”.
![navigation hierarchy on repo page](https://cloud.githubusercontent.com/assets/19801137/23655743/49045b6a-032e-11e7-9053-1015c31843ba.png)
![navigation hierarchy on build page](https://cloud.githubusercontent.com/assets/19801137/23655752/5130b81a-032e-11e7-96d2-2e34966a1f05.png)

**Comment by bartaz** [comment]
The breadcrumb should follow the pattern from Vanilla:
https://github.com/ubuntudesign/vanilla-design/tree/master/Breadcrumbs
