### ISSUE TITLE
Target platforms + workflow graphics are too similar + near

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#312]
The workflow graphic is too close in look to the target platforms.

---

Copied from Trello card: https://trello.com/c/tuoF3fw8/272-target-platforms-workflow-graphics-are-too-similar-near
Labels: design

**Comment by jamiedawsonyoung** [comment]
Tackling this in #361

**Comment by nottrobin** [comment]
@jamiedawsonyoung should this be closed?

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#312 Target platforms + workflow graphics are too similar + near](https://trello.com/c/QWoJpcI7/598-312-target-platforms-workflow-graphics-are-too-similar-near)

**Comment by matthewpaulthomas** [comment]
No longer treating as part of #361.
