### ISSUE TITLE
Spinner is 'in flow' which means when it appears it has to move elements below it down the page. [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#313]
Spinner should not be in flow and should sit in z-index with some kind of overlay, avoiding the case where buttons move away from the users pointer because the spinner appeared.

---

Copied from Trello card: https://trello.com/c/CTH7MTvB/307-spinner-is-in-flow-which-means-when-it-appears-it-has-to-move-elements-below-it-down-the-page
Labels:

**Comment by matthewpaulthomas** [comment]
<https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.43owh6tjv12q>: “When you choose ‘Add’, everything in the dialog should become disabled, and the text of the ‘Add’ button should change to a spinner.”
