### ISSUE TITLE
[dashboard] Spacing between user details, progress bar, first-time text, and main component

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#314]
The progress bar and first-time text look too closely packed, but I'm not sure what the proper spacing should be. Can someone from design provide guidance?

---

Copied from Trello card: https://trello.com/c/vXhusZok/245-dashboard-spacing-between-user-details-progress-bar-first-time-text-and-main-component
Labels: design

**Comment by matthewpaulthomas** [comment]
Duplicate of #223.

**Comment by cjwatson** [comment]
Closing as duplicate of #223, as above.
