### ISSUE TITLE
[Dashboard] Spacing between paragraphs and text colouring

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#315]
I think there should be slightly more spacing between "This repo needs a snapcraft.yaml …", "Learn the basics …", and "Don't have snapcraft …". The latter two should be grey, per the spec.

---

Copied from Trello card: https://trello.com/c/Tv1LII2N/243-dashboard-spacing-between-paragraphs-and-text-colouring
Labels: design

**Comment by matthewpaulthomas** [comment]
This is a duplicate of #226.
