### ISSUE TITLE
“Dashboard” is a confusing name [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#320]
We’ll probably have an actual dashboard for ISVs in the future, so we shouldn’t call our main screen “Dashboard”.

---

Copied from Trello card: https://trello.com/c/ra654Drs/258-dashboard-is-a-confusing-name
Labels:

**Comment by matthewpaulthomas** [comment]
In Trello, Jamie wrote:
> Some thoughts:
> - Build list
> - Builds

I wrote:
> It’s true that the Dashboard lists builds — but so do the pages for each individual repo. So “Build list” or “Builds” probably wouldn’t help distinguish which page you’re on.
>
> Teresa suggested “My repos”.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.or9ei8m7j2f0): changed to “My repos”.

**Comment by pmahnke** [comment]
@matthewpaulthomas is this about changing the url as well? or just the title on the page?

**Comment by bartaz** [comment]
There is no "My repos" title on the page. Currently "Dashboard" is only used in header link and in the URL.

So without changing URL this task would be only about changing header link (which is about to be removed anyway in #318.

I think that if we are getting rid of 'dashboard' as a name, we should also update URL , as it's clearly specified as `/user/:username`in spec doc.

**Comment by bartaz** [comment]
Fixed by #492
