### ISSUE TITLE
[Bug] Maybe not obvious that you are on the Dashboard

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#324]
During our walkthrough of the UI Feb 24th, Teresa suggested that it may not be obvious, when you are on the dashboard, that that’s where you are.

This might be exacerbated by the “Choose repos to add” dialog covering most of the dashboard the first time (at least) that you see it.

If this is a problem for users, perhaps one way to lessen it would be to highlight “Dashboard” in the header whenever you are on the dashboard.

---

Copied from Trello card: https://trello.com/c/lhzMhdtM/239-bug-maybe-not-obvious-that-you-are-on-the-dashboard
Labels: design

**Comment by magdalena-mirowicz** [comment]
may be fixed by other tickets #320 and #310
