### ISSUE TITLE
“Publish your software for” looks out of place

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#331]
1. Go to <https://build.snapcraft.io/>.

Currently, “Publish your software for” is one of only two headings on the page (the other being “What people are saying about Snapcraft”).

“Publish your software for” is also one of only two strings that use small caps (and the other one _isn’t_ the other heading).

This can be fixed by some combination of:
- having headings for more of the sections
- using consistent style for the headings.

[Pointed out by Teresa Vasi during design review.]

---

Copied from Trello card: https://trello.com/c/gZ2NbehG/220-bug-publish-your-software-for-looks-out-of-place
Labels: design

**Comment by jamiedawsonyoung** [comment]
Being covered by all the changes from #361

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [“Publish your software for” looks out of place #331](https://trello.com/c/TkLdXtrh/604-publish-your-software-for-looks-out-of-place-331)
