### ISSUE TITLE
[footer] social media icons are warm grey

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#335]
The footer is still using the warm grey from old ubuntu.com

---

Copied from Trello card: https://trello.com/c/AyjUMqTc/297-footer-social-media-icons-are-warm-grey
Labels: design

**Comment by jamiedawsonyoung** [comment]
Covered by changes in #361

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [social media icons are warm grey #335](https://trello.com/c/I47miqMC/605-social-media-icons-are-warm-grey-335)

**Comment by kwm14** [comment]
Updated in issue #654

**Comment by matthewpaulthomas** [comment]
The shade of grey is now #666. Is that what it’s supposed to be? If so, this can be closed.

**Comment by kwm14** [comment]
@matthewpaulthomas Yep that is the correct colour.
