### ISSUE TITLE
Bug: sign in SSO button doesn’t work in Chrome for iOS

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#337]
---

Copied from Trello card: https://trello.com/c/tGpfBNEV/309-bug-sign-in-sso-button-no-longer-works
Labels:

**Comment by matthewpaulthomas** [comment]
Supposedly this was fixed by #247. @evandandrea can you confirm?

**Comment by evandandrea** [comment]
@matthewpaulthomas just confirmed this is indeed fixed.

**Comment by cjwatson** [comment]
I suspect it was actually #222, but as long as it works. :-)
