### ISSUE TITLE
Ability to reopen snapcraft.yaml editor after initial commit [2]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#338]
From Evan in https://trello.com/c/58b036a0a703f3c476f4052e via https://trello.com/c/MSTYY4fr: “it'd be good to be able to get back to your snapcraft.yaml editor link after you've committed the first one.”

Probably this would involve making the “Configured” checkmark clickable, with a link to edit the existing file on github.com.

---

Copied from Trello card: https://trello.com/c/mjmMTbtL/302-ability-to-reopen-snapcraft-yaml-editor-after-initial-commit
Labels:

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.z52hzl9t29sg):
>## Configured: Editing snapcraft.yaml
> ![repo list with configured repo](https://cloud.githubusercontent.com/assets/19801137/23667994/8b7da28e-0357-11e7-9fd5-8d0baec762b2.png)
>…
