### ISSUE TITLE
[Dashboard] Table - expanded row with information about SSO - copy to be adjusted to create better onboarding experience

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#345]
---

Copied from Trello card: https://trello.com/c/0G2DpQRJ/236-dashboard-table-expanded-row-with-information-about-sso-copy-to-be-adjusted-to-create-better-onboarding-experience
Labels:

**Comment by matthewpaulthomas** [comment]
This was a brief comment during a design review in February, about the text: “To publish to the snap store, this repo needs a registered name. You need to sign in to Ubuntu One to register a name.”.

Unfortunately I don’t remember what the complaint was, and it doesn’t seem to be recorded anywhere, so I’m closing this.
