### ISSUE TITLE
[dashboard] Using colours in the progress meter

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#354]
Grazina thought it was odd that the progress meter uses three colours (green, blue, and grey) rather than two.

This is especially since the first time you see the meter, you are already on step two. At that point there’s one step in each colour, making it less obvious that they’re progress colours (rather than, say, step colours).

- Also look at the amount of colour (more delicate)

---

Copied from Trello card: https://trello.com/c/MUQPy1BO/298-dashboard-using-colours-in-the-progress-meter
Labels: design

**Comment by jamiedawsonyoung** [comment]
### Options for progress meter:
- Dots smaller and connecting lines thinner
- Only 2 colours (grey and green) used
- Current step uses a regular font weight (not light)

#### No steps complete (not sure you'd ever see this) 
![01-progress-meter-none](https://cloud.githubusercontent.com/assets/6909617/23709967/09008454-0413-11e7-89f8-d4301351f3f8.png)

#### Connect to GitHub
![02-progress-meter-github](https://cloud.githubusercontent.com/assets/6909617/23709969/0901a942-0413-11e7-9062-f7728d113035.png)

#### Choose a repo
![03-progress-meter-repo](https://cloud.githubusercontent.com/assets/6909617/23709968/09014ede-0413-11e7-92cf-b4c36f6989ac.png)

#### Name and YAML
![04-progress-meter-name](https://cloud.githubusercontent.com/assets/6909617/23709971/09069092-0413-11e7-81ef-5ed07b1a7b00.png)

#### All steps complete
![05-progress-meter-all](https://cloud.githubusercontent.com/assets/6909617/23709970/09066342-0413-11e7-9943-c6163dec709b.png)

@matthewpaulthomas Could you have a look at this as well :-)

**Comment by jamiedawsonyoung** [comment]
@matthewpaulthomas Please have a look at this when you've time. I want to review a bunch of these design issues with Marcus tomorrow as he's not in on Friday.

**Comment by jamiedawsonyoung** [comment]
Reviewed with @matthewpaulthomas and got the +1

Most of the changes are small, I've outlines them below: 

Incomplete step: 
- height: 32px
- width: 32px
- border-radius: 16px
- color: $color-mid-light

Current step: 
- height: 32px
- width: 32px
- border-radius: 16px
- border: 2px solid $color-positive
- background-color: #FFFFFF

Complete step
- height: 32px
- width: 32px
- border-radius: 16px
- background-color: $color-positive
- icon: https://build.staging.snapcraft.io/static/icons/c3015ff051a11c71c6d052c1aa732cd6.svg
  - width: 16px

Incomplete step line: 
- height: 2px
- width: 450%
- color: $color-mid-light

Complete step line: 
- height: 2px
- width: 450%
- color: $color-positive

*If you need anything else, just let me know*

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#354 Using colours in the progress meter](https://trello.com/c/q3HbBkTA/601-354-using-colours-in-the-progress-meter)
