### ISSUE TITLE
[Build detail] Providing instructions for debugging failed build [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#355]
---

Copied from Trello card: https://trello.com/c/pGN2BJQq/232-build-detail-consider-providing-instructions-for-debugging-failed-build
Labels:

**Comment by evandandrea** [comment]
Snapcraft doesn't currently have installation instructions for each distro. So let's use the snapcraft snap:

```
snap install --edge --classic snapcraft
snapcraft cleanbuild --debug
```

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.lxvgcss3u749):
> If the build failed:
>>To debug this build:
>>
>>snap install --edge --classic snapcraft # if you don’t have snapcraft already
>>snapcraft cleanbuild --debug
>>
>>Don’t have snapd installed? __Install it now__.
