### ISSUE TITLE
Target platform OS logos look vertically misaligned

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#358]
Possible solutions:

- Top alignment
- Top alignment of the text
- Baseline alignment of the text
- Bottom alignment

---

Copied from Trello card: https://trello.com/c/H35hKp4R/266-target-platform-os-logos-look-vertically-misaligned
Labels:

**Comment by jamiedawsonyoung** [comment]
Tackling this in #361

**Comment by jamiedawsonyoung** [comment]
Can we order the OS logos:

- Debian
- OpenSuse
- Archlinux
- Gentoo linux
- Fedora
- Ubuntu

This should help it to feel more balanced.

**Comment by nottrobin** [comment]
@jamiedawsonyoung if this is tackled in #361, is there any need for this issue to remain open?

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#358 Target platform OS logos look vertically misaligned](https://trello.com/c/JETOgVid/600-358-target-platform-os-logos-look-vertically-misaligned)

**Comment by magdalena-mirowicz** [comment]
@jamiedawsonyoung please add new design

**Comment by jamiedawsonyoung** [comment]
So I've listed the order above which helps to make the current list of logos feel more aligned and less janky. Please See above for this.
