### ISSUE TITLE
Add metric for GitHub accounts that have ever logged in [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#360]
This is complicated because we don't quite keep state at this level, only once they actually create an account, and switch deploys mean that there isn't anywhere to keep that state right now.  Choices seem to be having a local Prometheus instance which handles the aggregation and federates with IS Prometheus, or possibly a little PostgreSQL instance which we can keep account settings in (which I suspect we may end up needing eventually, but it's probably more work than justified in the short term).

- [x] Add PostgreSQL instance to deployments
- [x] Add basic local database integration (Bookshelf.js)
- [x] Update charm to generate knex configuration based on PostgreSQL relation
- [x] Run migrations on each deployment
- [x] Add `/metrics` endpoint
- [x] Export GitHub user count metric
- [x] Get firewall access opened from IS Prometheus to BSI appservers
- [x] Connect metrics to `kpi.canonical.com`

---

Copied from Trello card: https://trello.com/c/8OsVtwzz/317-add-metric-for-github-accounts-that-have-ever-logged-in
Labels: MWC priority

**Comment by cjwatson** [comment]
https://portal.admin.canonical.com/100730 is the next stage of this.

**Comment by cjwatson** [comment]
There's a panel for this on https://snappy.kpi.canonical.com/dashboard/db/incoming-wip-store-kpis now.  It's a bit minimal, but we can refine it from here.
