### ISSUE TITLE
[landing] Update front page / homepage as per the spec [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#361]
This is difficult to describe, but: The front page looks like a collection of components, rather than a page that tells a compelling story.

The solution might include one or more of:

- Reducing spacing between items
- Reordering items
- Changing the dotted lines to something else
- Using consistent heading style
- Adding headings to more items

[Independently noticed by Matthew and Teresa.]

---

Copied from Trello card: https://trello.com/c/vUlN37F2/267-landing-front-page-doesn-t-flow
Labels: design

**Comment by jamiedawsonyoung** [comment]
3 options for tackling the above issues as well as #316 #312 #358 

### All options
- I've added headings to each section (needs review by @matthewpaulthomas)
- Adjusted the order of the OS logos to help alignment issues
- Updated the workflow diagram based on feedback
- Made the row padding consistent

### Things I've not done
- Removed all the dotted divider lines. These are a current pattern for the web. I've minimised the usage of them as much as possible.
- Reduced the space between rows. This is a current pattern as well so to change this we'll need to make a proposal to the Vanilla Working Group


#### Option 1
![landing-page-01](https://cloud.githubusercontent.com/assets/6909617/23706150/ed3bf93c-0404-11e7-9b0c-b755ed3c6a22.png)
#### Option 2
![landing-page-02](https://cloud.githubusercontent.com/assets/6909617/23706157/f4f1a4b0-0404-11e7-882c-45060c6f1bad.png)
#### Option 3
![landing-page-03](https://cloud.githubusercontent.com/assets/6909617/23706165/fdb14772-0404-11e7-96e9-5caa694e7d9d.png)

(My preference is option 3 as it separates the other platform logos from the workflow diagram as well as elevating the explanation text on snaps) :-)

**Comment by bartaz** [comment]
I don't think 'Snaps' should be capitalized in "What people are saying about Snaps".

**Comment by jamiedawsonyoung** [comment]
### Option 4
- No capitalization on "snaps"
- Adjusted the workflow diagram after some discussion with @tiheum

![landing-page-04](https://cloud.githubusercontent.com/assets/6909617/23707383/0fbffbca-040a-11e7-9a06-6404065a2da4.png)

**Comment by jamiedawsonyoung** [comment]
### Option 5
- Revised the workflow diagram and checked with @yaili that could still be responsive. 
- New graphics for Snaps row including IoT graphics

![landing-page-07](https://cloud.githubusercontent.com/assets/6909617/23797083/082139be-0596-11e7-9410-f729f822c740.png)

**Comment by evandandrea** [comment]
Option 5 would be my preference. "Publish your software for" being moved to the bottom, as it was in option 4, buries an important point.

**Comment by jamiedawsonyoung** [comment]
@evandandrea 👍   Option 5 will tick off a lot of small cards so it's our preference too :-)

**Comment by evandandrea** [comment]
"The code lands on your GitHub branch" should be "The code lands on your GitHub master branch" or "The code lands on your GitHub master."

Branch by itself is ambiguous. Is it the branch I'm merging from or to?

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#361 Front page doesn’t flow](https://trello.com/c/6OqgQitT/594-361-front-page-doesn-t-flow)

**Comment by magdalena-mirowicz** [comment]
@jamiedawsonyoung please add links to new icons to this card

**Comment by jamiedawsonyoung** [comment]
The icons used in the "Fast, easy and safe" row are found in [this dropbox folder](https://www.dropbox.com/sh/bkkhoyae32bizn9/AAApTd6joBsLs081PHlnHtBba?dl=0). They're all in grey but can be changed to whatever colour necessary as they're svgs.

**Comment by carlaberkers** [comment]
@nottrobin @evandandrea marking this GA

**Comment by carlaberkers** [comment]
@matthewpaulthomas also include https://github.com/canonical-ols/build.snapcraft.io/issues/359

**Comment by evandandrea** [comment]
@carlaberkers @matthewpaulthomas is this still `Design: In progress`?

**Comment by matthewpaulthomas** [comment]
@evandandrea Implementing Jamie’s “Option 5”, as-is, would be an improvement. It would fix: 
- #312 Target platforms and workflow graphics are too similar+near
- #331 “Publish your software for” looks out of place
- #358 Target platform OS logos look vertically misaligned
- #335 social media icons are warm grey (though that’s not front-page-specific)

It would not fix:
- #316 Workflow diagram doesn’t make it obvious how we save you time/effort
- #359 Top of page looks insubstantial — little text

This report was marked as In Progress because we thought all these issues should be addressed at the same time. But the design for the remaining two may take a while, so probably it’s better not to delay this further.

**Comment by sparkiegeek** [comment]
@matthewpaulthomas @kwm14 

1) I've noticed that we've lost the colour gradient (and some termination symbols) on the lines in the topmost image, is that deliberate? If so, can you please upload the revised image to the asset server and let me know where it is?

2) This design suggests that we want to drop the Beta tag, is that correct?

3) Can you please colour the SVGs that Jamie linked to above (for the Fast, easy and safe) in his Dropbox and upload to the asset server?

4) https://assets.ubuntu.com/v1/9ec98fa2-workflow_text-to-path.svg needs updating to the new design, uploading to asset server

**Comment by evandandrea** [comment]
>2. This design suggests that we want to drop the Beta tag, is that correct?

I think that's reasonable so long as org support lands first.

**Comment by kwm14** [comment]
@sparkiegeek 

Looking at Jamie's 'Option 5' design above that doesn't reflect what's seen on build.snapcraft.io currently. I will locate the latest design and add to this repo as I believe it will cover most of your comments.

**Comment by sparkiegeek** [comment]
@kwm14 right, option 5 is what I'm working on implementing in this issue :) Just need those assets to make further progress.

**Comment by sparkiegeek** [comment]
> 1. I've noticed that we've lost the colour gradient (and some termination symbols) on the lines in the
> topmost image, is that deliberate? If so, can you please upload the revised image to the asset
> server and let me know where it is?

I'm using the revised hero image from #506 at the moment.

Still need 3. and 4.

**Comment by kwm14** [comment]
@sparkiegeek 

**3. Fast to install, easy to create, safe to run**
https://assets.ubuntu.com/v1/2c5e93c5-fast-easy-safe-illustration.svg

**4. How Snapcraft fits into your workflow**
https://assets.ubuntu.com/v1/88506392-workflow-illustration.svg

**Comment by evandandrea** [comment]
@kwm14 I think https://assets.ubuntu.com/v1/88506392-workflow-illustration.svg is missing the font. The old asset (https://assets.ubuntu.com/v1/9ec98fa2-workflow_text-to-path.svg) renders the text correctly for me.

**Comment by kwm14** [comment]
## Updated design

- based on all changes from these issues #656 #506 #335

![14-landing-page-beta](https://cloud.githubusercontent.com/assets/17748020/25956881/db5279f2-3664-11e7-93d2-223b7e007705.png)
