### ISSUE TITLE
[landing] Illustration needs to be brighter colours

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#362]
Look at brighter colours for the illustration

---

Copied from Trello card: https://trello.com/c/OytA0r3A/294-landing-illustration-needs-to-be-brighter-colours
Labels: design

**Comment by jamiedawsonyoung** [comment]
@tiheum worked on some options for this. 

**More saturated colours**
![colour-palette_saturated](https://cloud.githubusercontent.com/assets/6909617/23658723/8702acf2-033b-11e7-85ad-1354e27cbc51.png)

**Colours from the secondary palette (01)**
![colour-palette_secondary01](https://cloud.githubusercontent.com/assets/6909617/23658725/87047d34-033b-11e7-9d35-6bfe17cc6be2.png)

**Colours from the secondary palette (02)**
![colour-palette_secondary02](https://cloud.githubusercontent.com/assets/6909617/23658724/87036822-033b-11e7-9087-73f07cd20c98.png)

**Colours from the Vanilla palette (02)**
![colour-palette_vanilla](https://cloud.githubusercontent.com/assets/6909617/23658726/8705eb42-033b-11e7-807a-5aac0c2b6cbc.png)

Need to review these with @marcush

**Comment by jamiedawsonyoung** [comment]
Reviewed with Marcus, he's keen on the first version with the more saturated colours.

**Comment by jamiedawsonyoung** [comment]
Final assets, ready to add to the homepage. All assets are on the [assets manager](https://manager.assets.ubuntu.com)
- [Banner](https://assets.ubuntu.com/v1/64c2e521-workflow-saturated.svg)
- [Workflow](https://assets.ubuntu.com/v1/64c2e521-workflow-saturated.svg)

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#362 Illustration needs to be brighter colours](https://trello.com/c/newnIYys/596-362-illustration-needs-to-be-brighter-colours)
