### ISSUE TITLE
[Dashboard] Repo table row doesn’t auto-expand when no repos have a name yet

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#363]
Panel for registering snap name for the first repo opens automatically when user has at least one repo, but none have a name yet (and no other repos have ever been removed).

---

Copied from Trello card: https://trello.com/c/HAFdLZOo/234-dashboard-repo-table-row-doesn-t-auto-expand-when-no-repos-have-a-name-yet
Labels:

**Comment by earnubs** [comment]
Fixed in #450 & #484
