### ISSUE TITLE
Add the new logo to the site

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#364]
For now: let's use just "snapcraft"

---

Copied from Trello card: https://trello.com/c/n92pKPcg/88-site-wide-define-product-name-logo-branding
Labels: Blocked

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Define product name / logo / branding #364](https://trello.com/c/f7Woksiv/606-define-product-name-logo-branding-364)

**Comment by evandandrea** [comment]
I don't think the public launch should block on this. We decided at MWC to continue with the brandless design for now.

**Comment by jamiedawsonyoung** [comment]
So we've made a start on this via the [social media work for Snapcraft](https://docs.google.com/a/canonical.com/presentation/d/1xAayeYqqzYyDR5FgaqNNtcvUqfX3r6Cy1uUtf7n811A/edit?usp=sharing). But this will almost certainly change once Mark sees it.

**Comment by evandandrea** [comment]
We have an icon now: https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.7u5ojzzgsazp

**Comment by carlaberkers** [comment]
discussed this with Marcus, there is no logo for snapcraft and Mark has requested we not make one. 
the icon is not to be used as a logo @nottrobin @evandandrea @matthewpaulthomas @magdalena-mirowicz @pmahnke

**Comment by nottrobin** [comment]
@carlaberkers so this issue can be closed?
