### ISSUE TITLE
The "snap install" command-line instructions shouldn't be shown if there are no published builds

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#365]
---

Copied from Trello card: https://trello.com/c/lBJoCwEi/226-the-snap-install-command-line-instructions-shouldn-t-be-shown-if-there-are-no-published-builds
Labels: Blocked

**Comment by evandandrea** [comment]
This is occurring on the `/builds` page:

<img width="1054" alt="screen shot 2017-03-16 at 16 29 49" src="https://cloud.githubusercontent.com/assets/1523179/24007309/1083c5ac-0a66-11e7-87eb-80b7896d6f1d.png">

**Comment by magdalena-mirowicz** [comment]
duplicate of #528
