### ISSUE TITLE
[landing] Bullet points look like checkboxes

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#367]
The graphics for the bullet points (“Scale to millions of installs”, “Available on all clouds”, etc) look needlessly similar to checkboxes.

---

Copied from Trello card: https://trello.com/c/PwRlfpHq/263-landing-bullet-points-look-like-checkboxes
Labels: Blocked

**Comment by matthewpaulthomas** [comment]
They’re now green checkmarks instead. I’m not a fan of that (since the list isn’t a realistic customer checklist), but at least they don’t look like checkboxes any more.
