### ISSUE TITLE
[build detail] Launchpad API for publishing state of build

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#368]
https://code.launchpad.net/~cjwatson/launchpad/snap-store-upload-state-api/+merge/318396
---

Copied from Trello card: https://trello.com/c/lBs9NcL8/186-build-detail-launchpad-api-for-publishing-state-of-build
Labels: MWC priority

**Comment by cjwatson** [comment]
I've rolled this new API out to production now ([docs](https://launchpad.net/+apidoc/devel.html#snap_build)).  The new fields are `snap_build.store_upload_status`, `snap_build.store_upload_url`, and `snap_build.store_upload_error_message`.
