### ISSUE TITLE
Handle registered name not matching snap name [pt. 1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#369]
Should only cover detecting name mismatch and showing dropdown with "The snapcraft.yaml uses the snap name “{snapcraft.yaml name}”, but you’ve registered the name “{registered name}”." text

Additional conditions (and action links) from the spec will be covered separately.

---

Copied from Trello card: https://trello.com/c/zvLmZuMR/322-handle-registered-name-not-matching-snap-name-pt-1
Labels:

**Comment by pmahnke** [comment]
<img src="https://trello-attachments.s3.amazonaws.com/581b4f456a7f428516c7e24d/58b7e2b5555af9099afff819/850add7992e4763a6eee3e18b330548b/Repo_list_with_non-matching_names.png">

**Comment by pmahnke** [comment]
https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.wyo3cgnn0ubx

**Comment by bartaz** [comment]
Fixed by #262
