### ISSUE TITLE
[dashboard] Sort repos that need attention (are incomplete) first

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#378]
Comments:

Needs design spec,What are “actionable items”?

---
Creator: Robin Winslow
Assignees: Matthew Paul Thomas
Copied from Trello card: https://trello.com/c/5tLFvJA4/111-dashboard-sort-repos-that-need-attention-are-incomplete-first
Labels: design,Question,copy to github

**Comment by pmahnke** [comment]
From @matthewpaulthomas:   

> This would require a few hours of design work. However, I don’t think it’s useful. By the time anyone has enough repos for it to make a difference, they’ll have enough experience to easily find the repos that need work anyway. It certainly shouldn’t be a priority for public launch.

**Comment by matthewpaulthomas** [comment]
Teresa has agreed that [sortable columns](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.n3mre2f0woxt) (for example, sorting repos without registered names first) is enough for this. It’s not necessary (and would complicate the mental model a bit) to have a separate, non-column-specific, sorting for “need[s] attention”/“actionable” in general.
