### ISSUE TITLE
Update dashboard URL

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#382]
Currently we have dashboard at /dashboard

Current decision from design doc is to use `/user/:name` URL scheme.

https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU

Comments:

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/577iQuNy/153-update-dashboard-url
Labels: copy to github

**Comment by matthewpaulthomas** [comment]
Fixed a while ago.
