### ISSUE TITLE
Record git commit identifier of a snap build in LP

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#386]
Comments:

@magdalena_mir still valid,@colinwatson4  is it still valid? if not please move to done

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/rQN1tB2T/16-record-git-commit-identifier-of-a-snap-build-in-lp
Labels: copy to github

**Comment by cjwatson** [comment]
https://code.launchpad.net/~cjwatson/launchpad/db-snap-revision-id/+merge/321688
https://code.launchpad.net/~cjwatson/launchpad/snap-revision-id/+merge/321690
