### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#389]
MVP spec
========
https://docs.google.com/document/d/1Q9eZgLPYbTgzBEGsvvKnnnwPfrIpvfrsNkgsfRWMh5A

https://docs.google.com/document/d/1AKm_Qrq15BIJd5G93yvJVse-D7WG2ZK3CI08C6KdcHc/edit#bookmark=id.aoqvr4kaghws

#### Flow chart:
https://drive.google.com/a/canonical.com/file/d/0B43LShcd7qs1UWFybXBtMXZwYmc/view?usp=sharing

#### Text and design specification:
https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU

Launchpad
========
https://help.launchpad.net/API/Hacking

JavaScript
========

https://expressjs.com/ # server
https://facebook.github.io/react/ # components
https://github.com/reactjs/redux # state management
https://github.com/ReactTraining/react-router # routing

JS is compiled to es6 target inc. modules with https://babeljs.io/

Deployment
==========
https://wiki.canonical.com/ProductStrategyTeam/WebDevelopment/build.snapcraft.io

Comments:

The purpose of this card was to hold shared documentation links.  As such it remains valid (though should occasionally be updated): it's not a to-do card.,Is this still relevant? 

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/6Qeud6WD/17-docs
Labels: copy to github

**Comment by magdalena-mirowicz** [comment]
Copied to project folder
