### ISSUE TITLE
Build page empty

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#395]
https://zapier.com/engine/hydrate/54157/.eJwVjEEOgyAQAP-yZy_gQrs8ol8gK66VUGkjmzTG-PfS68xkTsi1KdckMc8QDKE3FnGAJctrjpU3gQCsymndpGqDAdIqqcQiBwSHxt06eVftMurx-eePHpUv788G4YTEez-Du08skydyI3k0xpFdRiQL1_UDQM8pRA:1ckrpC:mudyStXCvgDZr8UZlcdL7GFIww0/

Comments:

After adding a snap to the dashboard that had been added in the past, and using the template to create a yaml (with the name mailhog-lola).,404: https://build.snapcraft.io/api/launchpad/snaps?repository_url=https%3A%2F%2Fgithub.com%2Flolachangmwc2017%2Fmailhog
{"status":"error","payload":{"code":"snap-not-found","message":"Cannot find existing snap based on this URL"}}

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/Sl7OrMnS/344-build-page-empty
Labels: Bug,copy to github

**Comment by evandandrea** [comment]
Confirmed this is still occurring:

<img width="1027" alt="screen shot 2017-03-13 at 10 45 35" src="https://cloud.githubusercontent.com/assets/1523179/23851149/4ab9a3a6-07da-11e7-93be-09f044534fff.png">

<img width="1440" alt="screen shot 2017-03-13 at 10 45 48" src="https://cloud.githubusercontent.com/assets/1523179/23851164/52d535b4-07da-11e7-8aec-ce899406426c.png">

**Comment by bartaz** [comment]
This seemed to be related specifically with this MailHog repository.

It turns out we are internally lowercasing GitHub user name and repository name that we get in URL, so instead of `evandandrea/MailHog` we are looking for `evandandrea/mailhog` snap, which cannot be found (because git repo URLs are case sensitive).
