### ISSUE TITLE
Dashboard does not update when the build status changes

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#396]
Comments:

**Steps to reproduce:**

1. Add a repository with a snapcraft.yaml

**What happens:**

* The "Latest build" column stays on "Needs building" for the added repo.

**What should happen:**

* The "Latest build" column updates as the build progresses.

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/PFmNY8eg/340-dashboard-does-not-update-when-the-build-status-changes
Labels: copy to github

**Comment by magdalena-mirowicz** [comment]
May be fixed by #293

**Comment by bartaz** [comment]
Yes, seems to be fixed already.
