### ISSUE TITLE
"Name is reserved" does not guide the user to resolution [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#401]
<img width="1024" alt="screen shot 2017-03-04 at 15 24 29" src="https://cloud.githubusercontent.com/assets/19801137/23650069/c69ac9a8-0318-11e7-9d2c-051d4c6a5288.png">

Comments:

@matthewpaulthomas can you provide copy for this? Do you think there's enough room to embed the "reason for dispute" input box, so we can call the API for registering a dispute without needing to redirect to https://myapps.developer.ubuntu.com/dev/click-apps/register-name-dispute/?name=zeppelin?

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/jwV59HPA/338-name-is-reserved-does-not-guide-the-user-to-resolution
Labels: copy to github

**Comment by matthewpaulthomas** [comment]
@evandandrea What does “Name is reserved” mean?

If it means “taken by someone else”, [the spec already describes behavior for that](https://goo.gl/dYLsPe): “Sorry, that name is already taken. Try a different name. // If you think you should have sole rights to the name, you can __file a claim__.”

If it means “can’t be used by anyone”, then I don’t understand why you’d still be able to dispute it.

**Comment by evandandrea** [comment]
@matthewpaulthomas some names have been reserved by Canonical for the
publisher (e.g. firefox, zeppelin). These can be acquired through the
dispute mechanism:
https://myapps.developer.ubuntu.com/dev/click-apps/register-name-dispute/?name=zeppelin

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.sf9bdlnfvbkg): “Sorry, that name is reserved. Try a different name. // If you think you should have sole rights to the name, you can __file a claim__.”
