### ISSUE TITLE
Provide better sign-post back to build.s.io from committing initial snap/snapcraft.yaml on GitHub

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#404]
Comments:

So far this card covers several ideas:

- Evan: “be able to get back to your snapcraft.yaml editor link after you've committed the first one” — split off as https://trello.com/c/mjmMTbtL
- Colin: “just clos[ing] the tab … may not be obvious enough” — split off as https://trello.com/c/bjCH1Jpj
- Peter: “editing file in BSI UI” — split off as https://trello.com/c/9sTd13vi

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/MSTYY4fr/291-provide-better-sign-post-back-to-build-s-io-from-committing-initial-snap-snapcraft-yaml-on-github
Labels: copy to github

**Comment by evandandrea** [comment]
This is covered by #390, #293, and #338.
