### ISSUE TITLE
Update build statuses as per the spec [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#406]
Currently we show build statuses as returned by Launchpad.

We need to map those to values defined in design doc.

https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/

Comments:

@magdalena_mir Yes.
It's partly blocked on https://trello.com/c/lBs9NcL8/186-build-detail-launchpad-api-for-publishing-state-of-build 

But we are still showing build statuses directly from LP, while we should map them to messages (and colours) from the doc.,@bartoszopka  is it still valid? If not please move to done

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/SS7S6Q3t/149-update-build-status-names-and-colours
Labels: copy to github

**Comment by matthewpaulthomas** [comment]
Fixing this probably will fix #329 as well.
