### ISSUE TITLE
Hook up statsd and add basic metrics

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#408]
Comments:

@magdalena_mir yes,@colinwatson4 is this still valid? thanks

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/pbWvMGlj/63-hook-up-statsd-and-add-basic-metrics
Labels: copy to github

**Comment by cjwatson** [comment]
Superseded by the work in #360.
