### ISSUE TITLE
Robustness: proxy timeout

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#412]
The current network proxy timeout for snap builds is an hour, but there are some known builds that take longer than that on slower architectures.  We don't want the timeout to be infinite, but we can probably afford to increase it further.

Comments:

@colinwatson4 Thanks, just trying to prioritise :-),@jamiedawsonyoung yes,@colinwatson4 Is this still relevant? 

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/h5UHtShe/68-robustness-proxy-timeout
Labels: copy to github

**Comment by cjwatson** [comment]
https://portal.admin.canonical.com/100604
