### ISSUE TITLE
Don't take user to build page until log is available

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#416]
When the build has started but hasn't yet finished, there will be no log to view. We shouldn't send the user to the build page (where all they can see is an empty log). Instead we should just tell them that the build is in progress on the dashboard page.

**Comment by bartaz** [comment]
@nottrobin Should it only be done for 'Latest build' on dashboard?

If given repo has any build already (finished or in progress) the link to repo page will be available, and from there they will be able to get to "empty" build page anyway.

Also, currently we don't show empty log box (as it was before), but a message that says that build log will appear when build completes. Which looks better than before, but of course is still quite empty and useless page.

**Comment by nottrobin** [comment]
@bartaz I don't think any of this should apply to just the latest build, I think the same rules are true for all builds.

Yes the decision was that because the page is so empty when there is no build log, we should avoid even sending them there, instead simply telling them on the dashboard that the build is in progress. As soon as it's finished, the link to the build log page will appear. That's my understanding.
