### ISSUE TITLE
Document how to debug issues with the Jenkaas environment

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#433]
@cjwatson spent a while figuring out how to get a local debugging environment for the Jenkaas scripts working.

This should now be written down somewhere so that it's quicker and easier for the next person.

**Comment by cjwatson** [comment]
I've written up https://wiki.canonical.com/ProductStrategyTeam/WebDevelopment/build.snapcraft.io, including this bit of documentation.

**Comment by nottrobin** [comment]
Thanks @cjwatson that looks really great.
