### ISSUE TITLE
Missing myapps links for packages

### ISSUE THREAD

**Issue by caldav** [canonical-ols/build.snapcraft.io#441]
The homepage diagram ends with this tile:
![screenshot from 2017-03-09 10-00-10](https://cloud.githubusercontent.com/assets/18480003/23742978/3fd15b60-04af-11e7-803a-f08f03d7a3a6.png)

The relationship between the two services (build.s.io and myapps) is not apparent in the rest of the UI.

If build.snapcraft.io is intended to be a gateway to stable publication, the dashboard should probably have links to app pages (`https://myapps.developer.ubuntu.com/dev/click-apps/<package-number>`).

**Comment by cjwatson** [comment]
This might need design work, but as of recently it's at least doable in internal API terms: [snap_build](https://launchpad.net/+apidoc/devel.html#snap_build) now has a `store_upload_url` attribute.

**Comment by evandandrea** [comment]
@caldav we're going to be guiding them to stable publication using the command line. Is there another function present in myapps that you think is missing from the GitHub workflow?

**Comment by caldav** [comment]
A couple things: 
* all the available visual store front ends (snapweb, uappexplorer, ubuntu software) use the icon set in the store, not the one from the snap (until the snap is installed)
* The support, license and website fields (only consumed by uappexplorer, afaict) can only be set in myapps

The first one is the most important, because lack of icon in the store can really be catastrophic for awareness and credibility, but it could be something we fix on the store side by pulling the icon from the snap.

**Comment by evandandrea** [comment]
@caldav agreed, those sound like bugs we should fix. Now that we have download and upload deltas, I don't think it's unreasonable to set all metadata and the icon via a snapcraft push.

It would nicely handle the confusing situation where once you use myapps to set some metadata, forever is it sourced from there regardless of any change you make in the `snap/meta.yaml`.

**Comment by evandandrea** [comment]
@caldav filed https://bugs.launchpad.net/snapstore/+bug/1672660 for the icon issue and https://bugs.launchpad.net/snapstore/+bug/1672664 for the mysterious extra fields. Please feel free to add detail there.
