### ISSUE TITLE
Stress test of dashboard being up to date

### ISSUE THREAD

**Issue by magdalena-mirowicz** [canonical-ols/build.snapcraft.io#443]
Make sure every change to github repo or to registered name, or build status is reflected in the table. If there are any bugs not recorded yet, please file them and add to Public launch milestone.

**Comment by magdalena-mirowicz** [comment]
possibly to be sent to QA team

**Comment by matthewpaulthomas** [comment]
Issues already reported with the table not updating correctly: #293, #398, #453.

**Comment by evandandrea** [comment]
Closing this out. The state issues with the dashboard have been resolved (thanks!)
