### ISSUE TITLE
User should be able to reuse any name previously registered

### ISSUE THREAD

**Issue by magdalena-mirowicz** [canonical-ols/build.snapcraft.io#444]

**Comment by magdalena-mirowicz** [comment]
may be already working

**Comment by magdalena-mirowicz** [comment]
@jamiedawsonyoung please test

**Comment by jamiedawsonyoung** [comment]
# Tested 2 scenarios:
(based on comments from @bartaz @katiefenn on IRC)

### Scenario 1: 
1. add some repository
2. register a name for it
3. remove this repository
4. add same repository again
5. try to register same name for same (re-added) repository

This **worked** I could assign the same name back to the same repo even if I'd removed it and re-added it to my list.

### Scenario 2: 
1. add some repository
2. register a name for it
3. remove this repository
4. add ANOTHER repository
5. try register SAME name for this newly added different repo

This produced an **unexpected result** (for me anyway).
- The name was registered with a tick 
- I got an error on the configured column with a "Doesn't match" message
- The build still went ahead and successfully built.

Looking at the yaml file I can see why the error appeared but I wasn't sure it should build without both bits (name and yaml) being in sync?

**Comment by jamiedawsonyoung** [comment]
After some conversation on IRC channel: 

- The scenario we are testing is the first one and reported here: https://trello.com/c/KZfeFS7G
  - It works so no need for more work
- The second scenario shows something a bit odd but is correct.
  - We just need to correct the result label to "Built, won't be published" 
  - There's a card #368 that @cjwatson has finished which allows for this now
