### ISSUE TITLE
Instructions for promoting updates from edge to stable [1]

### ISSUE THREAD

**Issue by magdalena-mirowicz** [canonical-ols/build.snapcraft.io#445]
You should be given instructions for promoting updates from edge to stable, when you've determined they're ready for general consumption

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.lxvgcss3u749): “More text if this is the latest build, and snapcraft.yaml does not contain ‘confinement: devmode’…”

**Comment by evandandrea** [comment]
https://www.youtube.com/watch?v=p1b_syo6sgU though @popey might have time to work on one in more of a narrative style, for when you have a build.snapcraft.io created snap in the edge channel that you want to push to stable.

**Comment by jamiedawsonyoung** [comment]
Still awaiting visual design

**Comment by matthewpaulthomas** [comment]
This doesn’t need visual design: it’s plain text in an already-existing box.

**Comment by bartaz** [comment]
Instruction text:
```
snapcraft release {name of snap} {revision number} beta
snapcraft release {name of snap} {revision number} candidate
snapcraft release {name of snap} {revision number} stable
```

requires a revision number of given build, and we dont' have this information in BSI yet.

This ticket is blocked until we can get revision number for given build from LP.

**Comment by evandandrea** [comment]
That's https://github.com/canonical-ols/build.snapcraft.io/issues/304

**Comment by bartaz** [comment]
Unblocked by #596
