### ISSUE TITLE
RepositoryInput doesn't handle 401 gracefully

### ISSUE THREAD

**Issue by cjwatson** [canonical-ols/build.snapcraft.io#46]
If the user doesn't have GitHub credentials in their session (nobody will currently because that isn't fully hooked up yet, but even once it is it's a conceivable failure mode) then `/api/launchpad/snaps` will return 401, which currently causes `RepositoryInput` to say "Repository ${input.repository} doesn't exist, is not public or doesn't contain snapcraft.yaml file."  That's rather misleading, and we should behave less confusingly in this case.

**Comment by evandandrea** [comment]
Let me know if you want a separate issue for it, but I'm also seeing 422 when inputting any valid repo:

>POST https://build.staging.snapcraft.io/api/github/webhook 422 (Unprocessable Entity)
(anonymous) @ bundle.2c3b0ff….js:18
(anonymous) @ bundle.2c3b0ff….js:36
value @ bundle.2c3b0ff….js:25
r @ bundle.2c3b0ff….js:4
i @ bundle.2c3b0ff….js:4
s @ bundle.2c3b0ff….js:4
m @ bundle.2c3b0ff….js:3
p @ bundle.2c3b0ff….js:3
n @ bundle.2c3b0ff….js:23
processEventQueue @ bundle.2c3b0ff….js:3
r @ bundle.2c3b0ff….js:34
handleTopLevel @ bundle.2c3b0ff….js:34
a @ bundle.2c3b0ff….js:34
perform @ bundle.2c3b0ff….js:3
batchedUpdates @ bundle.2c3b0ff….js:34
a @ bundle.2c3b0ff….js:2
dispatchEvent @ bundle.2c3b0ff….js:34
bundle.2c3b0ff….js:3 POST https://build.staging.snapcraft.io/api/launchpad/snaps 400 (Bad Request)

**Comment by bartaz** [comment]
@evandandrea 422 from webhook may mean that webhook for given repo is already created, but for details you may check response body in browser console.

I guess the more interesting one would be 400 from POST https://build.staging.snapcraft.io/api/launchpad/snaps - I got one when I was trying to use repo that was already used before (also can be checked in error message in response).

We have it on our radar that we don't handle errors very well right now (they are not shown to user in a meaningful and actionable ways).

So thanks for the report. If you have any more details on the particular cases you've seen these errors let us know.

**Comment by evandandrea** [comment]
@bartaz it's as you suspected.

/webhook:
>{"status":"error","payload":{"code":"github-already-created","message":"A webhook already exists on the given repository"}}

/snaps:
>{"status":"error","payload":{"code":"lp-error","message":"There is already a snap package with the same name and owner."}}

Thanks!

**Comment by cjwatson** [comment]
@evandandrea The webhook case should be a separate issue because we're going to need to deal with that in a specialised way (webhook setup should be idempotent, basically).  The snap creation case will be dealt with by a few things in flight: #65 should show the error more sensibly, #66 will make it harder to get into this situation in the first place, and #63 accounts for the remaining difficulties.

**Comment by bartaz** [comment]
Mostly fixed already, covered also in #85 and as separate issue in #68
