### ISSUE TITLE
Failed builds suggest you can install the snap

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#462]
<img width="847" alt="screen shot 2017-03-13 at 11 25 07" src="https://cloud.githubusercontent.com/assets/1523179/23852468/d1c4ee82-07df-11e7-9bc0-95f6aabbf850.png">

When a build fails the "To test the latest successful build on your PC or cloud instance" message still appears. Likely fixed by #355.

**Comment by magdalena-mirowicz** [comment]
@evandandrea can you confirm if 355 fixed it? Thanks

**Comment by evandandrea** [comment]
355 fixed this. There's a lesser issue that I've filed as 528.
