### ISSUE TITLE
Labels for unregistered and unconfigured repos not action focused. 

### ISSUE THREAD

**Issue by jamiedawsonyoung** [canonical-ols/build.snapcraft.io#488]
The labels in the cells for unregistered and unconfigured are maybe too descriptive of what exsists and not suggestive of what is doable by the user (i.e to register and configure)

I wonder if something more like "Configure" and "Register" would be more instructional as to what the user needs to do?

**Comment by matthewpaulthomas** [comment]
This is a variation of the age-old question: whether a toggle control’s label should convey its current state (for example, “Locked”, “Connected”, “Not configured”), or the effect of clicking it (“Unlock”, “Disconnect”, “Configure”).

The usual approach is for the label to convey the current state, relying on graphical elements (pressed state, checkbox, switch, etc) to indicate the effect of clicking. Using the label to indicate the effect of clicking is reserved for controls where the visual design can’t convey the effect, whether through unfamiliarity or through not obviously being a toggle control at all: for example, the “Click the lock to make changes” pseudo-button in macOS System Preferences, or the “Show Details”/“Hide Details” button in Ubuntu’s error reporter.

I followed the usual approach in this case for two more reasons. First, the repo table is almost entirely a data table, so it’s even more of a norm to Show The Data.

Second, if you have 20 repos with registered snap names, labelling the cell by its effect would mean displaying “Change” or “Rename” 20 times. That would be both monotonous, and much less informative than showing the actual name of each snap. Then, if named snaps show the current state in their “Registered for publishing” cell, it’s consistent for them to show their current state in the “Configured” cell too.
