### ISSUE TITLE
Snapcraft badge

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#496]
We've talked about this, [even spec'ed it](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.a0779cz1kwjv), but had nothing to track progress. Let's have a snapcraft [badge](http://shields.io/) that links to the latest successful build with the image including the build date.

Not a requirement for the public launch.

**Comment by matthewpaulthomas** [comment]
People wouldn’t know this badge existed unless it was advertised somewhere in the UI. I guess it belongs on the repo page?

**Comment by evandandrea** [comment]
Yes, agreed. Repo singular.

**Comment by evandandrea** [comment]
Now a duplicate of #675
