### ISSUE TITLE
Use of laptop in published for your users graphic is confusing

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#506]
<img width="956" alt="screen shot 2017-03-16 at 16 43 23" src="https://cloud.githubusercontent.com/assets/1523179/24007871/cd7bad40-0a67-11e7-804b-f16b8532dba0.png">

Mark pointed out at MWC that the laptop image used above "published for your users" is confusing, that you think the laptop is you, the developer.

**Comment by jamiedawsonyoung** [comment]
We met with @evandandrea and he's going to propose a solution that @tiheum came up with to Mark. If that doesn't get an approval then he will ask Mark what other device he'd like in that spot and @tiheum can work on a new image.

**Comment by evandandrea** [comment]
Unfortunately I didn't get to meet with Mark yesterday.

**Comment by evandandrea** [comment]
Reached out to Mark via email.

**Comment by jamiedawsonyoung** [comment]
Going to pop this into "Blocked" until we get a response.

**Comment by kwm14** [comment]
Hi @evandandrea 

Did you get a reply from Mark regarding the device update in the proposed solution @jamiedawsonyoung mentioned above?

**Comment by evandandrea** [comment]
@kwm14 I didn't ever get a reply. Can we use a quadcopter (or some other obviously IoT image) for now?

**Comment by kwm14** [comment]
@evandandrea ok cool.

I spoke with Marcus and @tiheum about adding some form of IoT device in there, he said he will take a look but could prove difficult with a drone due to the graphic's perspective and the isometric shapes and angles used.

But I'll keep you updated.

**Comment by kwm14** [comment]
@evandandrea New hero illustration by @tiheum to include a drone, he created a few iterations which myself and Marcus reviewed and this design got sign-off.

### Updated hero illustration
![header04b](https://cloud.githubusercontent.com/assets/17748020/25941366/12816b4c-3631-11e7-802b-1692d6ebb864.png)

Let me know your thoughts and if all good I will attach SVG to update in build.

**Comment by evandandrea** [comment]
This is great! Thank you @tiheum and @kwm14!

**Comment by kwm14** [comment]
@evandandrea @sparkiegeek 

New hero illustration added to the asset server.

**Hero**
https://assets.ubuntu.com/v1/ed6d1c5b-build.snapcraft.hero.svg

**Comment by sparkiegeek** [comment]
@kwm14 hmm, this conflicts with https://github.com/canonical-ols/build.snapcraft.io/issues/361#issuecomment-285669710 which has grey lines and only end terminators (no blobs on the left)

**Comment by bartaz** [comment]
@sparkiegeek If that's the illustration that was signed off I guess it should be used instead of what designs in #361 show.

Use the designs for layout/styling, not copy text or specific illustrations. Thanks!

**Comment by matthewpaulthomas** [comment]
Fixed.
