### ISSUE TITLE
Call it beta for now, call out organisation repositories not being supported

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#515]
If we decide to launch without support for public organisation repositories, we'll want to draw greater attention to their absence. Much as I hate beta banners, I think we'll want one in this case.

**Comment by evandandrea** [comment]
We could extend the private repos (#309) message to say:
>2 selected of 38 public repos (private and organisation repos not shown)

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Call it beta for now, call out organisation repositories not being supported #515](https://trello.com/c/WlpPtTDh/616-call-it-beta-for-now-call-out-organisation-repositories-not-being-supported-515)

**Comment by evandandrea** [comment]
@matthewpaulthomas @jamiedawsonyoung what do we think of explicitly calling out the lack of organisation repos support in that beta banner?

**Comment by jamiedawsonyoung** [comment]
@evandandrea @matthewpaulthomas I'm not sure we should call it out in the banner. Only because the banner will probably be one of the first things the user sees at the top of the landing page and it might put them off going any further?

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Call it beta for now, call out organisation repositories not being supported #515](https://trello.com/c/gGUo8K2U/618-call-it-beta-for-now-call-out-organisation-repositories-not-being-supported-515)

**Comment by magdalena-mirowicz** [comment]
split into #535 and #534
