### ISSUE TITLE
Debugging instructions don't mention checking out the repo, other issues [1]

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#524]
Apologies, this is my fault. The debugging instructions don't mention checking out the repo before running `snapcraft cleanbuild --debug`:

<img width="1035" alt="screen shot 2017-03-20 at 11 11 11" src="https://cloud.githubusercontent.com/assets/1523179/24097591/71fd788c-0d5e-11e7-8317-f62400c929b0.png">

As well,
* `snap install` requires you be logged in or that you run it with `sudo`
* cleanbuild requires lxd ([using the snap is broken, but fixed soon](https://bugs.launchpad.net/snapcraft/+bug/1666735))

So this should instead be:
```
sudo snap install lxd # if you don't have LXD already
sudo snap install --classic --edge snapcraft # if you don't have snapcraft already

git clone https://github.com/evandandrea/telegram-snap
cd telegram-snap
snapcraft cleanbuild --debug
```

Where https://github.com/evandandrea/telegram-snap should change based on the repo and commit hash that triggered this build.

**Comment by evandandrea** [comment]
From Sergio on the 2.28 release, which will fix `snapcraft cleanbuild` requiring a deb-installed lxd:
>this week, dput into -proposed thursday or friday and to edge as well, we can get a beta on thursday/friday as well, depending on a couple of bugs we need to fix

**Comment by cjwatson** [comment]
We don't have the commit hash available right now (#386), but I'd also contend that giving the "git checkout" line there is unnecessary.  Developers will probably just want to debug the failure on their master branch anyway, since that will be the target of any PRs they produce, and if the problem has gone away between the commit that failed and the tip of master then it's all good.

**Comment by evandandrea** [comment]
Yeah, fair point. Fixing.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.fb6xz08fuya5).
