### ISSUE TITLE
"Registered for publishing" name always ends as "Unauthorized" [1]

### ISSUE THREAD

**Issue by mwinter-osr** [canonical-ols/build.snapcraft.io#527]
Trying to build snap with the "build.snapcraft.io".
Registering the project through the github works fine, but then when I try to register the snap name, I always get "Unauthorized". The snap already exists and is registered to my account. But trying to use some new (unregistered) name doesn't work either.
There is no other error - just the "Unauthorized" response.

(This is on repo Github:mwinter-osr/frr-snapcraft-io, trying to register to "frr" snap)

While it is blocking me from using build.snapcraft.io, it is not an urgent issue anymore as I moved to use launchpad directly and all works fine from within launchpad.

**Comment by evandandrea** [comment]
Hi @mwinter-osr,

When did you try this? I cannot reproduce this, but it sounds like a duplicate of #444 which landed a few days back.

Thanks!

**Comment by mwinter-osr** [comment]
In my case, I never managed to register a name at all. I've tried with a name which is registered to me (didn't work) and a name which didn't exist yet (didn't work).

The other scenarios describe all a case where registering a name (at least once) worked.

So I think this is a different issue.

**Comment by evandandrea** [comment]
I've just tried the following:

1. Registered a name outside of build.snapcraft.io
1. Changed my `snapcraft.yaml` in GitHub to use the new name
1. Added the repo on build.snapcraft.io

What happened:

- The repo showed up with the name "not registered"
- Clicking on "not registered" gave me the option to register with the name from the snapcraft.yaml pre-filled
- Clicking the sign in button to register the name took me back to the dashboard with the name showing as registered

Are you experiencing something else? What happens when you try with a name that doesn't exist yet? Can you take a screenshot of the error state with the javascript console open?

I'll admit it's confusing that the UI doesn't show the name as registered to you initially. At this early point we just know your GitHub identity. We don't know what account you're registered in the store as.

**Comment by mwinter-osr** [comment]
Attached are some screenshots.
One is from before I click the register name and the 2nd from afterwards.

There seems to be a unexpected "401 error" just after logging into the Ubuntu One Account.
I have verified that the login is fine and going to "https://login.ubuntu.com/" even shows me
the last access from build.snapcraft.io" and my snap registered.

One difference (to your description) is that I have previously uploaded the snap directly from
the https://myapps.developer.ubuntu.com/dev/click-apps/ web - so there is already an existing snap. 

![screen shot 2017-03-21 at 3 39 28 pm](https://cloud.githubusercontent.com/assets/1490788/24174297/2634df04-0e4d-11e7-87c7-70b055d89b52.png)
![screen shot 2017-03-21 at 3 40 38 pm](https://cloud.githubusercontent.com/assets/1490788/24174302/28097830-0e4d-11e7-93a4-0024d1e6c5c9.png)

**Comment by elopio** [comment]
I'm also getting unauthorized when trying to build ipfs. I already own the ipfs name, so I shouldn't even have to click a button called `register`.

**Comment by bartaz** [comment]
Seems like some issue with macaroons used to authorize API calls to store.

Hard to say much without reproducing it but it looks like macaroons we get after signing in to Ubuntu One are then not accepted by the store when we try to register the name.

**Comment by noise** [comment]
I encountered this as well, trying to add a new repo and register a new name to go with it, consistently Unauthorized regardless of what name I try to use.

**Comment by cjwatson** [comment]
Could somebody who can reproduce this please use devtools to extract the full content of the response (headers and body) and show it to us?  It's possible it won't help much, but it may let us narrow things down a bit.

**Comment by magdalena-mirowicz** [comment]
@developer please investigate this issue and timebox it to 1 day. Then please correct the estimate if more work needed, and we can discuss the priority

**Comment by earnubs** [comment]
2:08 PM <beowulf> fgallina: o/ anything about this ring any bells? https://github.com/canonical-ols/build.snapcraft.io/issues/527
2:47 PM <fgallina> beowulf: so, from the report it looks like a 401? that means that it doesn't even get as far as preconditions_check (i.e. checking if the macaroon has package_upload_request or package_upload and agreement and namespace checks) Is the HTTP_AUTHORIZATION passed correctly? are you sure it's being passed a valid macaroon?
2:48 PM <fgallina> beowulf: that's all I can think of.

**Comment by noise** [comment]
On page load (after logged in):

Request: https://build.snapcraft.io/api/store/account?root=MDA....
Response: 401 / {"error_list":[{"message":"Authorization Required","code":"macaroon-permission-required"}]}

Then when I enter a name and click Register Name:
Request: https://build.snapcraft.io/api/store/register-name
Response: 401 / {"error_list":[{"message":"Authorization Required","code":"macaroon-permission-required"}]}

**Comment by cjwatson** [comment]
@noise Could you extract the response headers as well?  `WWW-Authenticate` in particular, but we might as well get a dump of anything non-sensitive if possible.

**Comment by cjwatson** [comment]
@noise The other thing you could usefully do, if possible, would be to extract your raw macaroon from the request and run it through something like this:

    from pymacaroons import Macaroon
    print(Macaroon.deserialize(raw_macaroon).inspect())

There'll be some secret information there that you should elide, but it'd be really helpful to see the rest of it.

**Comment by noise** [comment]
@cjwatson hmm, neither reponse has an auth header, here's the full headers for the register-name request:

```
HTTP/1.1 401 Unauthorized
Date: Mon, 03 Apr 2017 19:58:34 GMT
Server: Apache/2.4.18 (Ubuntu)
X-VCS-Revision: f4e5b8b787607a3d29bf994c6ff37707ce19121d
X-DNS-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Type: application/json; charset=utf-8
Content-Length: 91
ETag: W/"5b-qoE5SHVchDWgGWCgEVy+HA"
X-Request-Id: WOKpan8AAQEAAErDZW4AAABf1
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
```

**Comment by cjwatson** [comment]
As well as the PR here to log more information on the BSI side, I've proposed https://code.launchpad.net/~cjwatson/software-center-agent/log-macaroon-failures/+merge/321848 to see if we can get more logging of this on the SCA side.

**Comment by noise** [comment]
@cjwatson here's both macaroons:

discharge:

identifier {"secret": "[REDACTED]", "version": 1}
cid login.ubuntu.com|account|[REDACTED]
cid login.ubuntu.com|valid_since|2017-04-04T17:56:58.365224
cid login.ubuntu.com|last_auth|2017-04-04T17:56:58.365224
cid login.ubuntu.com|expires|2018-04-04T17:56:58.365284

root:

location myapps.developer.ubuntu.com
identifier MyApps
cid myapps.developer.ubuntu.com|valid_since|2017-04-04T17:56:57.458495
cid {"secret": "[REDACTED]", "version": 1}
vid [REDACTED]
cl login.ubuntu.com
cid myapps.developer.ubuntu.com|channel|["edge"]
cid myapps.developer.ubuntu.com|expires|2017-04-04T15:56:56.895000
cid myapps.developer.ubuntu.com|acl|["package_upload_request", "edit_account"]

**Comment by cjwatson** [comment]
Having `expires` be earlier than `valid_since` is certainly exotic.

I wonder if this is a timezone issue ...
