### ISSUE TITLE
Repo page suggests testing when there isn't a published build yet [1]

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#528]
<img width="1038" alt="screen shot 2017-03-21 at 09 07 11" src="https://cloud.githubusercontent.com/assets/1523179/24139910/f8b0b90e-0e15-11e7-8f7a-d88b581abf1b.png">

What happens:
- No builds have been successful
- Instructions are shown to install the snap from edge

What should happen:
- No instructions are shown

**Comment by matthewpaulthomas** [comment]
[This is already in the spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.i96r6cjhu8ob): “Text if the snap has been published”. If it hasn’t been published, it shouldn’t be there.

**Comment by evandandrea** [comment]
👍 Changed the request from debugging text to no text.
