### ISSUE TITLE
[beta] banner asking for feedback [1]

### ISSUE THREAD

**Issue by magdalena-mirowicz** [canonical-ols/build.snapcraft.io#534]

**Comment by jamiedawsonyoung** [comment]
### We've had sign-off on the design of: 
- Header beta flag
- Feedback notification banner

#### Assets / specs
Beta flag:
- https://assets.ubuntu.com/v1/e8ac33d1-header-beta-flag.svg
- Align to the right of the snapcraft.io logo
  - margin-left: 8px

Feedback banner: 
- Use the style from Vanilla: https://docs.vanillaframework.io/en/patterns/notification
- **Text to read:** "Hey, got a spare five minutes to give us some feedback?" 
  - Link "give us some feedback"
- Remove icon: https://assets.ubuntu.com/v1/89c10794-remove.svg
  - 16x16px
  - Aligned right
  - Same padding as text

**Any other styling questions, please ping me…**

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[beta] banner asking for feedback #534](https://trello.com/c/oPgoMiGY/621-beta-banner-asking-for-feedback-534)

**Comment by evandandrea** [comment]
From @jamiedawsonyoung 
>@evandandrea @matthewpaulthomas I'm not sure we should call it out in the banner. Only because the banner will probably be one of the first things the user sees at the top of the landing page and it might put them off going any further?

I want to convey somewhere that organisation repos are not available but coming *soon*. This is different to private repos, which carry no urgency to supporting them.

**Comment by bartaz** [comment]
@jamiedawsonyoung

Couple of questions to clarify:

1. When should the 'banner' be shown to user and on what pages (I recall it should be after they signed in to BSI, but it's not specified anywhere)?

2. When user closes the banner - should it ever be shown to them again? On next login? Or never?

**Comment by jamiedawsonyoung** [comment]
@bartaz 

Couple of answers :-)

- It should appear on all the pages once the user is logged in (so not the landing page)
    - We think a decent guess is it should appear after they've been on a page for **2 mins**
      - This should really be dictated by Google Analytics. I'm trying to get access to this for a more accurate time for you… (but go with 2 mins for now)

2. No, they don't need to see this again (it would be annoying)
