### ISSUE TITLE
[beta banner] Embedding google form survey [1]

### ISSUE THREAD

**Issue by magdalena-mirowicz** [canonical-ols/build.snapcraft.io#535]

**Comment by jamiedawsonyoung** [comment]
Decided with Teresa and Matthew to allow this to open in a new tab. The link to the form is here: 

https://docs.google.com/forms/d/e/1FAIpQLSeCAKWHb4w-iNrg-YqyiRVMHULDlZMx9bXyK9a7s40sXYjQzQ/viewform?usp=sf_link

**Comment by bartaz** [comment]
Form linked as part of #534 (fixed in #546)
