### ISSUE TITLE
snap name textfield is too small

### ISSUE THREAD

**Issue by elopio** [canonical-ols/build.snapcraft.io#539]
The name of the snap I'm trying to publish is ipfs, but the text field height is not enough so the p and the f are cut, as seen in the screenshot.

![selection_008](https://cloud.githubusercontent.com/assets/617831/24268664/1e9d1b7a-0fd4-11e7-8065-a44be3a64462.png)

This is firefox 50.1.0 in Ubuntu Zesty, 1366x768, font size 16.

**Comment by bartaz** [comment]
Name registering UI will be updated as part of #465, so it should fix this issue.

**Comment by nottrobin** [comment]
Closing - coveredin #468
