### ISSUE TITLE
Navigation events trigger full page reload [2]

### ISSUE THREAD

**Issue by earnubs** [canonical-ols/build.snapcraft.io#542]
Navigation is triggering a full page reload rather than changing history state.

**Comment by earnubs** [comment]
This might be related to Google Tag Manager code but I can't see the munchkin tags that were added, GTM is showing me the Page View tag as empty https://tagmanager.google.com/?hl=en#/container/accounts/42438660/containers/1014405/workspaces/116/folders

<img width="495" alt="gtm" src="https://cloud.githubusercontent.com/assets/167440/24293371/542d20b8-1089-11e7-9acd-35933981478f.png">

**Comment by earnubs** [comment]
I see a `clickLink` xhr request in console then the page is reloaded.

**Comment by bartaz** [comment]
I mark it as a Beta launch bug as it's quite serious performance issue.

Also, while I work on beta notification right now, having page reload on each link click will totally mess up delayed showing of the notification (what is meant to work on simple setTimeout).

**Comment by bartaz** [comment]
After some debugging in tag manager we ended up configuring new separate tracking container for BSI #595 to limit the influence of click tags configured for other sites.

For now it seemed to help with the issue.
