### ISSUE TITLE
Element locator ids for QA automation

### ISSUE THREAD

**Issue by bartaz** [canonical-ols/build.snapcraft.io#567]
To simplify automation of e2e tests we need to add unique identifiers (preferably as HTML ids) for most elements on a page. Most notably actionable elements (links, buttons) and elements with generated content (user name in header, snap name in install instructions, etc).

From implementation point of view, these need to be unique and deterministic ids (so they don't change randomly between the builds for example).
But also we want to avoid hardcoding them in components, especially in those that are reused in multiple instances.
We need to come up with some good convention to generate those ids (maybe based on component name?).

Also it's worth noting that we need to add them simply everywhere in the app (all components and pages have those), so it's not a small chunk of work and may be worth splitting into smaller bits.

**Comment by bartaz** [comment]
For more context mail exchange:

Iftikhar Ahmad:
> I was going through the build.snapcraft.io website to see what we need if and when we go for test automation and realize that in general it doesn't have locator ids which can uniquely identify UI elements in a fixed manner. I understand it uses ReactJS to dynamically generate data-reactids, class names etc but as far as I know this is an implementation detail which can change over time and can't be used for selenium based automation. So, would it be possible to have unique and fixed locator attributes (name, id, class etc) for the UI elements to write repeatable and reliable tests going forward?

Bartek Szopka:
> Do you have any specific conventions for naming elements for your
automated tests?
>
> As you said - in React app there are data-reactids, but we shouldn't
rely on them as they are internal react implementation.
>
>For our own small test suite for my.ubuntu.com we used data-qa
attribute on elements to identify them in selenium tests, like this:
https://github.com/canonical-ols/my.ubuntu.com/blob/master/src/common/components/payments-form/index.js#L238
>
>We could probably incorporate the same convention for build.snapcraft.
Right now we don't have it anywhere, so it would need to be added - it
would be good to have a list of elements that would need to be
identified at the beginning - I suppose all of the buttons, maybe also
links between the pages could use that?

Iftikhar Ahmad:
> No specific convention and would rather prefer to go with standard id attribute as long as it is unique in a given page and then name, css, xpath in order of preference.
>
> As you said, these would be needed for all UI controls (buttons, progress bars, check boxes etc), links and any text items which requires to be verified e.g. user name on the header after signing in or "sudo snap install --edge my-snap-name" text on the builds page.

**Comment by earnubs** [comment]
Please don't use @id, it'll be abused at some point, use @data-qa as it's self documenting and decoupled from behaviour.

**Comment by iahmad9** [comment]
Ok, if that's what you prefer though github auth page also uses id and name attributes but I won't insist on that. I am fine as long as there is something to reach efficiently and consistently to the element of interest.

**Comment by magdalena-mirowicz** [comment]
@bartaz changing the milestone - automated tests can be added post beta launch

**Comment by evandandrea** [comment]
@magdalena-mirowicz can we close this out?

**Comment by magdalena-mirowicz** [comment]
sure
