### ISSUE TITLE
app should stop automated requests when page is not visible

### ISSUE THREAD

**Issue by earnubs** [canonical-ols/build.snapcraft.io#582]
When the user does not have the app in focus, the app should not poll external services, in order to lessen burden on those services and user's bandwidth. This could be handled via the Page Visibility API and perhaps setting some application level value in state.

https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
http://caniuse.com/#feat=pagevisibility

**Comment by bartaz** [comment]
Seems duplicate of #508

**Comment by earnubs** [comment]
Duplicate of #508
