### ISSUE TITLE
Gateway timeout on "Keep me posted"

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#617]
<img width="477" alt="screen shot 2017-04-11 at 09 50 38" src="https://cloud.githubusercontent.com/assets/1523179/24900693/8a093778-1e9c-11e7-97f8-73c41034b6eb.png">

Clicking "Keep me posted" results in a 504 on https://build.staging.snapcraft.io/api/subscribe/private-repos?email=evan%40dandrea.co.uk with:
```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

**Comment by bartaz** [comment]
```
<cjwatson> bartaz: my first-pass guess would be that it's not allowed by squid.internal and needs to be added to lp:canonical-is-puppet templates/squid/squid.internal.erb
<cjwatson> bartaz: but that'd want confirming
```

May be the case that API calls to our MailChimp form (https://canonical.us3.list-manage.com/subscribe/post-json) need to be allowed in squid proxy settings.

**Comment by cjwatson** [comment]
The combination of #626 and https://code.launchpad.net/~cjwatson/canonical-is-puppet/bsi-mailchimp/+merge/322436 should sort this out, once they both land.
