### ISSUE TITLE
Organisations: List organisation repositories on the "add repositories" page, so they can be added to the dashboard [4]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#620]
- [ ] Ensure organisation repository information is being pulled from GitHub on sign-up
- [ ] Ensure already added organisations are greyed out
- [ ] List organisation repositories in /select-repositories
- [ ] Ensure organisation repositories can be added to the dashboard
- [ ] We need to ensure that only repositories for which the user is an "admin" are shown

**Comment by nottrobin** [comment]
We need to ensure that only repositories for which the user is an "admin" are shown

**Comment by matthewpaulthomas** [comment]
As I see it, there are five possibilities. You can add a repo if:
A. You’re the owner
B. You have Admin permission, and if it’s an organization repo, you’re a member of the organization
C. You have Admin permission (even if you’re an outside collaborator)
D. You have Write permission, and if it’s an organization repo, you’re a member of the organization
E. You have Write permission (even if you’re an outside collaborator).

I thought yesterday’s conclusion was that we weren’t going to pay any attention to whether someone was an admin, ruling out B or C. So I’m not sure why “We need to ensure that only repositories for which the user is an ‘admin’ are shown”. @evandandrea can you clarify?

(If we do pay attention to whether someone is an admin, we’ll need to notice and handle the case of an admin being demoted. But we need to handle the equivalent case for Write permission anyway.)

**Comment by nottrobin** [comment]
@matthewpaulthomas This list was meant to be exhaustive in the sense that many of the items may happen implicitly or already be the case, it's just a check list. the reason the user needs to be an admin is because only then can we setup the webhooks.

**Comment by bartaz** [comment]
Only admins can add webhooks, so user needs to be an admin on given repository to add it to BSI (set up a webhook on GH to connect repo to LP).

So I guess we shouldn't list any repos that user cannot add - so we should only list repos where user in an admin (regardless of ownership of the repo: user, org, collaborator).

When user logs in (and first time authorizes BSI to access their GH) they give us rights and choose which of their orgs to allow us access. So by listing all user repositories we will get a list of all repos user has access to (own, collaboration, orgs). From that list we should filter only those where user is admin so they can effectively add it to BSI (set up the webhook).

**Comment by cjwatson** [comment]
I've proposed https://code.launchpad.net/~cjwatson/launchpad/snap-find-by-url-prefixes/+merge/323035 as a prerequisite for this.  (In order for it to be reasonable to list organisation repositories on the "add repositories" page, we need added repositories to show up on the "my repositories" page once you've added them; and to do that in a way that doesn't have terrible performance, we need something like this LP change.)

**Comment by cjwatson** [comment]
The LP change above is now on production, and I'm proceeding with the BSI side of things.
