### ISSUE TITLE
New snap is created even if name is not registered

### ISSUE THREAD

**Issue by bartaz** [canonical-ols/build.snapcraft.io#63]
Even if requesting creating new snap fails with `BadRequestPackageUploadResponse` that snap name is not registered, snap is already created anyway.

This means, that once the name is finally registered, user cannot create snap again (because snap for given repository is already created).

**Comment by bartaz** [comment]
@cjwatson not sure if that is somehow addressed in #62 or maybe related to your create webhook after snap trello card.

**Comment by cjwatson** [comment]
Not so much #62, but create-webhook-after-snap certainly helps.  There's still other cleanup to do in the event of a failure.

In the specific case at hand, though, we should be checking for snap name registration in advance so that we don't attempt to create the snap if the name is not registered.

**Comment by cjwatson** [comment]
commit 3931597411a2895fcd3cd367cb1150cdbea4a866
Author: Bartek Szopka <bartaz@users.noreply.github.com>
Date:   Fri Jan 6 12:29:58 2017 +0100

    Verify if snap name is registered before requesting new snap (#74)

    * Moved requesting new snap to new function

    * Requesting store macaroon to verify if snap name is registered

    * Moved Macaroon API URL to config

    * Fixing tests to properly mock macaroon API requests

    * Added tests for failed macaroon when name is not registered

    * Moving tests to nested contexts to avoid duplicating the same mocked server responses
