### ISSUE TITLE
Warn owners deleting organisation repositories that others won't be able to register them

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#647]

**Comment by evandandrea** [comment]
I thought we said this wasn't an issue?

1. Robin selects canonical-webteam/documentation-builder
1. Robin registers the documentation-builder snap name
1. Robin removes the repository
1. Carla adds the repository
1. Carla sees that the name is already registered and is instructed to register a claim
1. Carla registers a claim
1. Carla's claim is approved, the name is reassigned to her, and automated snap builds start

**Comment by nottrobin** [comment]
Yes, Carla will have a route to get ownership of the name, but the "contact canonical" step is still a pain. I thought we agreed that we should still notify at the registration point? But I'd be delighted to be wrong about that decision.

**Comment by evandandrea** [comment]
Let's see how often this happens in practice before investing time in smoothing it over.
