### ISSUE TITLE
Organisations: Also show organisation repositories on "my repos" dashboard even if you're not admin [2]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#648]

**Comment by matthewpaulthomas** [comment]
[Specification updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.5c3e9xiupuq5): “The ‘Repos to build and publish’ table should list all repos for which, if an automatic build or publication failed, you could potentially fix it. That is, all repos where you have write permission, whether you or someone else added them, and whether personal, internal organization collaborator, or external collaborator. (This avoids confusion about whether removing an organization repo will just hide it from view, or will stop it from auto-building: it is always the latter, just like with a personal repo.)”
