### ISSUE TITLE
Add Youtube to "follow-us" social links in footer [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#654]
Also, https://github.com/canonical-websites/snapcraft.io/issues/310

**Comment by evandandrea** [comment]
https://www.youtube.com/snapcraftio

**Comment by nottrobin** [comment]
@matthewpaulthomas could you provide the youtube social icon for the footer?

**Comment by matthewpaulthomas** [comment]
I suggest that a visual designer draw this at the same time as fixing #335.

**Comment by kwm14** [comment]
@nottrobin please find updated social sprite for footer, adding YouTube and new Google+ icon whilst updating colours to `$color-mid-dark` to fit in-line with our other Cloud products.

**Updated social sprite**
https://assets.ubuntu.com/v1/7faf3a04-build.snapcraft.social.svg

**Comment by matthewpaulthomas** [comment]
Thanks @kwm14. [Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.61iagpou0oq8). The YouTube link should be last in the group, for consistency with [the buttons on repo pages](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.dwvfeg899834) where you can post a snap installation link to the other sites but not to YouTube.

**Comment by kwm14** [comment]
@matthewpaulthomas I have updated social footer sprite according do the wireframes in your spec.

**Revised social sprite**
https://assets.ubuntu.com/v1/349a9e36-icon-social-snapcraft.svg

**Comment by katiefenn** [comment]
Is this Sprite correct? There are several changes in the above file besides the mentioned changes:

- Facebook and G+ sprites have switched places
- The sprite currently in the fourth column has disappeared entirely - the YouTube sprite has replaced it
- The position of each sprite does not match the current sprite - the guttering has slightly changed.

Compare:
https://assets.ubuntu.com/v1/349a9e36-icon-social-snapcraft.svg (supplied)
with
https://build.snapcraft.io/static/icons/ba3fd6fbbc639378c2e6f37f43cb812c.svg (current)

**Comment by kwm14** [comment]
@katiefenn Yes the latest Sprite supplied is the correct one.

- YouTube has replaced the original 'Canonical' icon as it's not relevant
- Position has changed so it's consistent with social sprites used on our all Cloud products

**Comment by katiefenn** [comment]
Thanks @kwm14 👍

**Comment by katiefenn** [comment]
@kwm14: Could you check the alignment of the icons, please? Some of the "active" icons are misaligned with their "inactive" equivalents on the horizontal axis. This is making the icons twitch when the mouse hovers over them.

**Comment by kwm14** [comment]
@katiefenn I have reviewed the icon and you were correct. In Sketch when you group a component it adds a 1px border so this was causing alignment issues. I have resolved this issue and exported a new version. Let me know if this is ok?

**Updated social sprite**
https://assets.ubuntu.com/v1/ea75daef-build.snapcraft.social.svg
