### ISSUE TITLE
Organisations: Update first-time visitor logic for organisation support [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#665]
As discussed in the workshop:

If a user visits the site for the first time, we should check for any organisation repositories that have already been added to build.snapcraft.io by a different user within the same organisation.

If they have any, the "Add repos" list should *not* be shown, and instead they should be taken straight to the "My repos" dashboard page which should list any organisation snaps.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.q0b3jpi4vtot): “No repos present, and none added in the past”.

**Comment by cjwatson** [comment]
I believe that I covered this in #690: `/api/launchpad/snaps/list` lists any relevant enabled organisation repositories, and the `RepositoriesHome` component redirects to `/select-repositories` if that endpoint returns a list of non-zero size.
