### ISSUE TITLE
Confirm all snap "name mismatch" conflict cases match spec [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#667]
Check that each of the cases mentioned in [the "name mismatch" section of the spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.wyo3cgnn0ubx) work as specified.

There are probably already a bunch of cards for these cases already. If you find them, please link them to this issue, and then if we confirm they're all covered elsewhere we can close this issue.

**Comment by matthewpaulthomas** [comment]
The linked section of the spec already included links to the issue report for each case. Of those, #300 was implemented before the initial beta/GA prioritization, and #298 and #299 were not prioritized as beta/GA.

**Comment by matthewpaulthomas** [comment]
I’ve now reported three more issues, and linked to each from the spec:
- #703 “Doesn’t match” > “Name mismatch”
- #704 Name mismatch doesn’t handle case where snapcraft.yaml has no name at all
- #705 Name mismatch omits suggestions for how to fix the problem

**Comment by katiefenn** [comment]
# Cell
[ ] Registered name "kfenn-667-test-registered", no name in snapcraft.yml
[ ] Registered name "kfenn-667-test-registered", snapcraft.yml name "kfenn-667-test-not-registered"
[ ] snapcraft.yml name "cjwatson-test-face-detection-demo"
[ ] snapcraft.yml name "kfenn-667-test-already-registered"
[ ] snapcraft.yml name "kfenn-667-test-invalid-"

# Dropdown
[ ] Registered name "kfenn-667-test-registered", no name in snapcraft.yml
[ ] Registered name "kfenn-667-test-registered", snapcraft.yml name "kfenn-667-test-not-registered"
[ ] snapcraft.yml name "cjwatson-test-face-detection-demo"
[ ] snapcraft.yml name "kfenn-667-test-already-registered"
[ ] snapcraft.yml name "kfenn-667-test-invalid-"

**Comment by matthewpaulthomas** [comment]
Those screenshots show, in order:

> Registered name "kfenn-667-test-registered", no name in snapcraft.yml

#704 Name mismatch doesn’t handle case where snapcraft.yaml has no name at all 

> Registered name "kfenn-667-test-registered", snapcraft.yml name "kfenn-667-test-not-registered"

#705 Name mismatch omits suggestions for how to fix the problem

> Registered name "kfenn-667-test-registered", snapcraft.yml name "cjwatson-test-face-detection-demo"
(not authorised)

#705 again (I don’t think it should make a difference whether you’re signed in)

> (authorised)

#226 Spacing between paragraphs and text colouring

> Registered name "kfenn-667-test-registered", snapcraft.yml name "kfenn-667-test-already-registered"
(not authorised)

#705 again

> (authorised)

#226 again

> Registered name "kfenn-667-test-registered", snapcraft.yml name "kfenn-667-test-invalid-"

#298 [name not matching] snapcraft.yaml name is invalid
