### ISSUE TITLE
Update renaming snap text to warn of marooning users [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#670]
Renaming a snap could result in users of that snap never receiving any more updates - this should be accurately communicated as per the spec. @matthewpaulthomas is the spec up-to-date for this?

**Comment by evandandrea** [comment]
[Relevant part of the spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.cihlhmeh60a0)

**Comment by matthewpaulthomas** [comment]
Yes, it is.
