### ISSUE TITLE
This site should be mentioned in snapcraft documentation

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#674]
Specifically on [the "Build and publish from Git" page](https://snapcraft.io/docs/build-snaps/ci-integration).

Do we want to do this immediately? In which case we should [create an issue against snappy-docs](https://github.com/CanonicalLtd/snappy-docs/issues/new) (or create a PR ourselves). Or should we wait until the official "launch"?

**Comment by evandandrea** [comment]
Filed as https://github.com/CanonicalLtd/snappy-docs/issues/72

I don't think we need to keep this issue around.
