### ISSUE TITLE
Name mismatch doesn’t handle case where snapcraft.yaml has no name at all

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-ols/build.snapcraft.io#704]
1\. Add a repo.
2\. If the repo doesn’t have one already, add a snapcraft.yaml that does not contain a “name” key.
3\. Register a name for the repo.
4\. Click the “Doesn’t match”/“Name mismatch” (#703) cell.

What you see: ‘The snapcraft.yaml uses the snap name “”, but you’ve registered the name “mpt-test-quieuriueriueiu”.’

What’s wrong with this: The snapcraft.yaml does not use the name “” — it doesn’t include a name at all. This case didn’t occur to me during the initial design.

[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.wyo3cgnn0ubx): “‘This repo has the registered name “{registered name}”. To allow publishing, add that name to the snapcraft.yaml.’ … the link “Add that name to the snapcraft.yaml” … should open, in a new window/tab, GitHub’s editor for editing the snapcraft.yaml file.”

**Comment by evandandrea** [comment]
Can be handled by #548.
