### ISSUE TITLE
Warning missing when changing snap name

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#728]
[The spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.cihlhmeh60a0) suggests the following message should be present and emphasised:
>Devices with the snap already installed will no longer receive updates.

This is missing on staging:
<img width="993" alt="screen shot 2017-05-05 at 12 17 34" src="https://cloud.githubusercontent.com/assets/1523179/25754362/dcf96216-318c-11e7-95ef-34e0b8ca0ffd.png">

**Comment by bartaz** [comment]
Seems to be already implemented (on staging):

<img width="1046" alt="screen shot 2017-05-05 at 18 56 22" src="https://cloud.githubusercontent.com/assets/83575/25755801/ab1b262a-31c4-11e7-95ab-b30dbc486264.png">

Visible only if build is already published.

**Comment by evandandrea** [comment]
Clever! I had missed that note about it only showing on publication.
