### ISSUE TITLE
Key phrases aren’t bold in “Any repos missing from this list?” text

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-ols/build.snapcraft.io#749]
1\. Choose “Add repos…”
2\. Choose “Any repos missing from this list?” or (if the text has been fixed) “Any missing?”

What you see: The popup is entirely plain text.

What you should see: [These phrases should be bold](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.msdazl1vu8u7):
- private repo
- organization
- admin permission
- wrong GitHub account
- pushed your code

**Comment by evandandrea** [comment]
Looks to be fixed on staging.
