### ISSUE TITLE
Font missing in workflow diagram

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#773]
<img width="1013" alt="screen shot 2017-05-16 at 09 16 23" src="https://cloud.githubusercontent.com/assets/1523179/26096242/653276c0-3a18-11e7-9b6d-a2e0e5b56c08.png">

Staging right now is missing the Ubuntu font for the workflow diagram.

**Comment by bartaz** [comment]
I think we had this issue before (#215)

If the diagram was updated the SVG needs to have font as vectors.
Can you provide updated image @kwm14 ?

**Comment by kwm14** [comment]
Interesting. Seems to be working for me when viewing in my browser.

@bartaz please find updated infographic with text as outline.

**Outlined workflow infographic**
https://assets.ubuntu.com/v1/6b571fb8-workflow-illustration.svg

**Comment by evandandrea** [comment]
Looks correct

**Comment by bartaz** [comment]
@kwm14 When browser renders SVG it uses system fonts, so if you have Ubuntu font in your OS, SVG will look fine. But when Ubuntu font is on in OS it will not show up correctly (even if browser is rendering rest of the text correctly thanks to web font).

**Comment by kwm14** [comment]
@bartaz aahhhh I see. Thanks for letting me know....you learn something new everyday :)

**Comment by earnubs** [comment]
@kwm14 to add to what @bartaz said, in the original the font is defined in the SVG much like in CSS:

```
<text xmlns="http://www.w3.org/2000/svg" id="You-receive-a-pull-r" font-size="16" font-family="Ubuntu-Light, Ubuntu" line-spacing="24" font-weight="300" fill="#333333">
      <tspan y="15" x="15.84">You receive a pull</tspan>
      <tspan y="39" x="12.64">request on GitHub</tspan>
     </text>
```

But if the system doesn't have Ubuntu font it'll switch to default, which is usually a serif font, unless you tell it otherwise in the SVG. Converting the text to paths means it's a larger SVG, but no dependency on fonts.
