### ISSUE TITLE
non 200 responses from `/api/launchpad/builds` are ultimately handled incorrectly in the reducer

### ISSUE THREAD

**Issue by earnubs** [canonical-ols/build.snapcraft.io#774]
In dev, error in console looks like: `snap-builds.js:55 Uncaught (in promise) TypeError: Cannot read property 'error' of undefined`

https://github.com/canonical-ols/build.snapcraft.io/blob/master/src/common/reducers/snap-builds.js#L55 should probably be `action.payload.error`

**Comment by bartaz** [comment]
Likely related:

![Uploading Screen Shot 2017-05-16 at 10.24.56.png…]()

**Comment by bartaz** [comment]
Seems to be happening not only for 'random' errors, but when user session expires:

<img width="800" alt="screen shot 2017-05-16 at 12 40 19" src="https://cloud.githubusercontent.com/assets/83575/26102365/f8924bc2-3a34-11e7-909a-aba90d4be975.png">

We keep polling for user snaps and even after getting 401 error we keep polling for snaps and their builds.
Errors are only visible in user console, UI is responsive but not fully functional.
User needs to sign out or reload whole page to get signed out.
