### ISSUE TITLE
Tell the difference between new user and user with no repos

### ISSUE THREAD

**Issue by bartaz** [canonical-ols/build.snapcraft.io#780]
To fully support application flow as in spec in relation to #665, #657, #755 we need to be able to tell the difference between first time user (who doesn't have any repos yet) and user who did have some repos, but now does not (because they removed it or their org repos were removed by other admins).

Specifically it applies to "...and none added in the past" part of the spec.

@matthewpaulthomas For implementation we need to clarify what does "...and none added in the past" mean in terms of organization repos.

If user didn't add any repos by himself, but did have some organization repos in "My repos" (added by someone else) that are now removed - should such user be treated as first time user (who didn't add any repos), or should they be treated as user who had some repos "added in the past"?

**Comment by bartaz** [comment]
As mentioned before by @cjwatson - implementing this feature means that users will not be able to get back to 'first time user' state. Also we - for testing - will not be able to get back to 'first time user' state without creating new GH account (or deleting contents of metrics db).

Currently users who remove all of their repos from BSI are treated in the same way as if they were new users.
If we implement the check if user added any snaps in the past we persist the data about the user without being able to delete it (unless we remove it from metrics db).

We currently don't have any 'delete account' functionality in BSI, so there will be no way for any user to get back to 'first time user' state once they sign in and add any repo.

@evandandrea @matthewpaulthomas Can you confirm that that's what we want to have implemented?

**Comment by matthewpaulthomas** [comment]
@bartaz Yes it is. “Get back to ‘first time user’ state” is not a goal for anyone except build.snapcraft.io developers doing QA. So the cost is that QA will be more difficult until account deletion is implemented. The benefit is that if, for example, someone was using build.snapcraft.io at a company for years but they’ve just been laid off, when they return to the site to use it for a personal project, we won’t be acting like we’ve never seen them before.
