### ISSUE TITLE
Shows "Cannot find existing snap based on this URL" briefly

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#79]
![screen shot 2017-01-06 at 13 41 52](https://cloud.githubusercontent.com/assets/1523179/21719645/c124c702-d416-11e6-8972-56b7b3bf6e39.png)

The /builds page defaults to showing "Cannot find existing snap based on this URL" while it loads. This is eventually replaced by the build list, but on a slow connection it proves confusing.

I don't think this is a particularly high priority issue; just noting it.

**Comment by cjwatson** [comment]
Yeah, I've seen this once myself, but it vanished when I tried to reproduce it.  It's definitely on my list to track down.

**Comment by evandandrea** [comment]
Awesome, thank you
