### ISSUE TITLE
Workflow diagram on front page scrapes the window edge in Firefox

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-ols/build.snapcraft.io#796]
1\. In Firefox, go to [the front page](https://build.snapcraft.io/).
2\. Resize the window to less than 1030px wide.
3\. Scroll to the workflow diagram.

What you see: The diagram touches the sides of the window.

What you should see: There should be consistent spacing between the sides of the diagram and the sides of the window. (What that spacing should be, I don’t know.)

**Comment by bartaz** [comment]
Duplicate of #795
