### ISSUE TITLE
Current UI does not match behaviour of spec for missing snapcraft.yaml

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#93]
<img width="394" alt="screen shot 2017-01-18 at 10 19 34" src="https://cloud.githubusercontent.com/assets/1523179/22056212/a943d682-dd67-11e6-8fb4-53822e798bb2.png">

The current UI prevents the user from proceeding if they do not have a snapcraft.yaml in their repository. This should only be a warning, as demonstrated in [the spec](https://docs.google.com/document/d/1AKm_Qrq15BIJd5G93yvJVse-D7WG2ZK3CI08C6KdcHc/edit#bookmark=id.lprwwnt70mzf).

We want to be able to quickly walk customers through the process of hooking their repositories up to the edge channel and only later loop back with them on the more time consuming task of crafting a snapcraft.yaml file.

Users coming to this website without a deep prior understanding of snaps are not going to have a snapcraft.yaml in their repository already, but it would be nice for them to cover this task off and work on that independently.

**Comment by bartaz** [comment]
To make the flow as in the spec we first need to add listing of repositories once user logs into their GH account.

But a temporary 'fix' could be to change the error message we show when there is no snapcraft.yaml into something like "Register your app name and add snapcraft.yaml to your repository" (with links to name registering and snapcraft.yaml docs).

**Comment by matthewpaulthomas** [comment]
Fixed weeks ago.
